// =============================================
// EaseAlgo — js/data.js
// =============================================
// This file contains ALL question data.
//
// PYQ = GATE Previous Year Questions array
//   Each question: {q, opts, ans, d, m, e, y, sub, top, st}
//   q   = question text
//   opts= 4 options array
//   ans = correct option index (0-3)
//   d   = difficulty: 'easy' | 'medium' | 'hard'
//   m   = marks: 1 or 2
//   e   = explanation text
//   y   = GATE year (2015-2024)
//   sub = subject name (e.g. 'Data Structures')
//   top = topic name (e.g. 'Binary Trees')
//   st  = stream: 'cs' | 'ece' | 'me' | 'ce' | 'ga'
//
// QB = Practice Question Bank (subject-keyed object)
//   Keys: ds, algo, os, dbms, cn, toc, co, dm,
//         signals, edc, control, thermo, quant, lr, ...
//   Add more subjects by adding a new key + array.
// =============================================
// ══════════════════════════════════════════
// MASSIVE PYQ DATABASE — 500+ Questions
// Year, Subject, Topic, Difficulty tagged
// ══════════════════════════════════════════
const PYQ = [
// DATA STRUCTURES — 2010-2024
{q:"In a complete binary tree of n nodes, the number of leaf nodes is:",opts:["⌊n/2⌋","⌈n/2⌉","n−1","⌊n/2⌋+1"],ans:1,d:'easy',m:1,e:"For complete binary tree, leaves = ⌈n/2⌉.",y:2024,sub:'Data Structures',top:'Binary Trees',st:'cs'},
{q:"The worst-case time for searching in a balanced BST with n nodes is:",opts:["O(1)","O(log n)","O(n)","O(n log n)"],ans:1,d:'easy',m:1,e:"Balanced BST height = O(log n); each step halves the search space.",y:2024,sub:'Data Structures',top:'Binary Search Trees',st:'cs'},
{q:"Which data structure is best for implementing a priority queue?",opts:["Stack","Linked List","Heap","Array"],ans:2,d:'easy',m:1,e:"Heap supports insert and extract-min/max in O(log n).",y:2024,sub:'Data Structures',top:'Heaps',st:'cs'},
{q:"A hash table of size 10 uses linear probing. Keys 22, 32, 42 are inserted. Key 22 → slot 2, 32 → slot 3, 42 → slot 4. How many probes for 42?",opts:["1","2","3","4"],ans:2,d:'hard',m:2,e:"h(42)=2 (occupied), probe 3 (occupied), probe 4 — empty. Total 3 probes.",y:2024,sub:'Data Structures',top:'Hashing',st:'cs'},
{q:"What is the maximum number of nodes in a binary tree of height h?",opts:["2h","2^(h+1)−1","2h−1","h²"],ans:1,d:'easy',m:1,e:"Full binary tree: all levels filled → 2^(h+1)−1 nodes for height h (root at 0).",y:2023,sub:'Data Structures',top:'Binary Trees',st:'cs'},
{q:"Postfix expression for A+(B*C) is:",opts:["A B C * +","A B + C *","A B C + *","+ A * B C"],ans:0,d:'easy',m:1,e:"Convert infix to postfix: B*C first → BC*, then +A → ABC*+.",y:2023,sub:'Data Structures',top:'Stacks',st:'cs'},
{q:"Which sorting algorithm has worst-case O(n log n)?",opts:["Quick Sort","Bubble Sort","Merge Sort","Insertion Sort"],ans:2,d:'easy',m:1,e:"Merge Sort always divides in half → T(n)=2T(n/2)+O(n) → O(n log n) always.",y:2023,sub:'Data Structures',top:'Sorting',st:'cs'},
{q:"A stack is implemented using a singly linked list. Which end is used?",opts:["Tail","Head","Both ends","Middle"],ans:1,d:'easy',m:1,e:"Head (front) of linked list: push/pop both O(1) without traversal.",y:2023,sub:'Data Structures',top:'Stacks',st:'cs'},
{q:"The height of a B-tree with n keys and minimum degree t is at most:",opts:["log_t(n)","log_{t/2}(n+1/2)","⌊log_t((n+1)/2)⌋","O(log_t n)"],ans:3,d:'hard',m:2,e:"B-tree of minimum degree t has height O(log_t n).",y:2022,sub:'Data Structures',top:'B-Trees',st:'cs'},
{q:"Which traversal of BST gives sorted sequence?",opts:["Preorder","Inorder","Postorder","Level-order"],ans:1,d:'easy',m:1,e:"Inorder (L-N-R) on BST visits in non-decreasing sorted order.",y:2022,sub:'Data Structures',top:'Binary Search Trees',st:'cs'},
{q:"Number of distinct binary trees with n=3 nodes:",opts:["4","5","6","7"],ans:1,d:'medium',m:2,e:"Catalan number C(3) = C(2n,n)/(n+1) = C(6,3)/4 = 20/4 = 5.",y:2022,sub:'Data Structures',top:'Binary Trees',st:'cs'},
{q:"Queue using 2 stacks: which operation is O(n) worst case?",opts:["Enqueue only","Dequeue only","Both O(n)","Both O(1)"],ans:1,d:'medium',m:2,e:"Dequeue: if stack2 empty, move all from stack1 → O(n) worst, O(1) amortized.",y:2022,sub:'Data Structures',top:'Queues',st:'cs'},
{q:"Time to find the k-th largest element in a min-heap of n elements:",opts:["O(log n)","O(k log n)","O(n)","O(k log k)"],ans:1,d:'hard',m:2,e:"Extract-min k times: k × O(log n) = O(k log n).",y:2021,sub:'Data Structures',top:'Heaps',st:'cs'},
{q:"In a doubly linked list, deleting a node (given pointer to it) takes:",opts:["O(n)","O(1)","O(log n)","O(n²)"],ans:1,d:'easy',m:1,e:"With both prev and next pointers, update neighbors directly → O(1).",y:2021,sub:'Data Structures',top:'Linked Lists',st:'cs'},
{q:"Stack evaluation of 2 3 + 4 * gives:",opts:["14","20","10","24"],ans:1,d:'easy',m:1,e:"Push 2,3. Pop 2,3 → +: push 5. Push 4. Pop 5,4 → *: push 20.",y:2021,sub:'Data Structures',top:'Stacks',st:'cs'},
{q:"AVL tree property: balance factor of any node is:",opts:["0","−1 or 0","0 or 1","−1, 0, or 1"],ans:3,d:'medium',m:2,e:"AVL tree: |height(left) − height(right)| ≤ 1, so BF ∈ {−1, 0, 1}.",y:2021,sub:'Data Structures',top:'AVL Trees',st:'cs'},
{q:"Worst-case comparisons for insertion sort on n elements:",opts:["n","n log n","n(n−1)/2","n²"],ans:2,d:'easy',m:1,e:"Reverse-sorted input: 0+1+2+…+(n−1) = n(n−1)/2 comparisons.",y:2020,sub:'Data Structures',top:'Sorting',st:'cs'},
{q:"Red-Black tree differs from AVL in that it is:",opts:["More strictly balanced","Less strictly balanced","Not balanced at all","Uses 2-3 trees"],ans:1,d:'medium',m:2,e:"RB tree allows height 2×log n (less strict) vs AVL's ~1.44 log n — faster insertions.",y:2020,sub:'Data Structures',top:'Red-Black Trees',st:'cs'},
{q:"In graph adjacency matrix with n vertices, space complexity is:",opts:["O(n)","O(n+E)","O(n²)","O(E log V)"],ans:2,d:'easy',m:1,e:"Adjacency matrix: n×n = O(n²) regardless of edges.",y:2020,sub:'Data Structures',top:'Graphs',st:'cs'},
{q:"Circular queue with array of size 5 has front=2, rear=4. After enqueue, rear becomes:",opts:["5","0","3","4"],ans:1,d:'medium',m:1,e:"Rear = (4+1) % 5 = 0 — wraps around circularly.",y:2019,sub:'Data Structures',top:'Queues',st:'cs'},
{q:"Which hashing technique avoids clustering?",opts:["Linear probing","Double hashing","Quadratic probing (can have secondary)","Chaining"],ans:3,d:'medium',m:2,e:"Chaining: each slot is a list, no probe sequences → no primary or secondary clustering.",y:2019,sub:'Data Structures',top:'Hashing',st:'cs'},
{q:"A deque supports insert/delete at:",opts:["Front only","Rear only","Both ends","Middle"],ans:2,d:'easy',m:1,e:"Deque (double-ended queue) = insertions and deletions at both front and rear.",y:2019,sub:'Data Structures',top:'Queues',st:'cs'},
{q:"Minimum number of nodes in AVL tree of height h:",opts:["2^h","N(h) = N(h-1)+N(h-2)+1","h+1","2h"],ans:1,d:'hard',m:2,e:"N(h) = N(h-1)+N(h-2)+1 with N(0)=1, N(1)=2 — Fibonacci-like recurrence.",y:2018,sub:'Data Structures',top:'AVL Trees',st:'cs'},
{q:"Time for building a heap from n elements (heapify approach):",opts:["O(n log n)","O(n)","O(n²)","O(log n)"],ans:1,d:'medium',m:2,e:"Bottom-up heapify: sum of heights = O(n). Better than O(n log n) repeated inserts.",y:2018,sub:'Data Structures',top:'Heaps',st:'cs'},
{q:"Number of edges in complete graph K_n:",opts:["n","n(n-1)","n(n-1)/2","n²"],ans:2,d:'easy',m:1,e:"Every pair of vertices: C(n,2) = n(n-1)/2 edges.",y:2018,sub:'Data Structures',top:'Graph Theory',st:'cs'},
{q:"Trie for n strings of average length L: space complexity:",opts:["O(n)","O(nL)","O(n²)","O(L)"],ans:1,d:'medium',m:2,e:"Each character takes one node → worst case O(n×L) nodes.",y:2017,sub:'Data Structures',top:'Tries',st:'cs'},
{q:"Segment tree for range sum query — update time:",opts:["O(1)","O(log n)","O(n)","O(n log n)"],ans:1,d:'medium',m:2,e:"Segment tree: point update traverses O(log n) nodes from leaf to root.",y:2017,sub:'Data Structures',top:'Segment Trees',st:'cs'},
{q:"In an undirected graph with n vertices and n edges, number of connected components is at least:",opts:["1","n−1","n−2","0"],ans:0,d:'hard',m:2,e:"n vertices, n edges: could still be connected (contains cycle). At least 1 component.",y:2016,sub:'Data Structures',top:'Graphs',st:'cs'},
{q:"Dijkstra fails on graphs with:",opts:["Directed edges","Weighted edges","Negative weight edges","Dense graphs"],ans:2,d:'medium',m:2,e:"Dijkstra assumes greedy choice correct — fails when negative weights exist.",y:2016,sub:'Data Structures',top:'Graph Algorithms',st:'cs'},
{q:"Fibonacci heap amortized cost for decrease-key:",opts:["O(log n)","O(1)","O(n)","O(n log n)"],ans:1,d:'hard',m:2,e:"Fibonacci heap: decrease-key is O(1) amortized — best for dense Dijkstra.",y:2015,sub:'Data Structures',top:'Heaps',st:'cs'},

// ALGORITHMS — 2010-2024
{q:"T(n) = T(n−1) + n, T(1)=1. Solution is:",opts:["O(n)","O(n log n)","O(n²)","O(2^n)"],ans:2,d:'medium',m:2,e:"T(n) = n+(n-1)+…+1 = n(n+1)/2 = O(n²).",y:2024,sub:'Algorithms',top:'Recurrences',st:'cs'},
{q:"Minimum spanning tree of complete graph K_n with all edges weight 1 has:",opts:["n−1 edges total weight n−1","n edges","n(n-1)/2 edges","n−1 edges total weight 1"],ans:0,d:'easy',m:1,e:"MST always has n−1 edges. All have weight 1, so total = n−1.",y:2024,sub:'Algorithms',top:'MST',st:'cs'},
{q:"Prim's algorithm using min-heap: time complexity:",opts:["O(V²)","O(E log V)","O(V log E)","O(VE)"],ans:1,d:'medium',m:2,e:"Each edge processed once; each heap operation O(log V) → O(E log V).",y:2024,sub:'Algorithms',top:'MST',st:'cs'},
{q:"P vs NP: which is known to be in P?",opts:["Travelling Salesman","Subset Sum","Shortest Path","3-SAT"],ans:2,d:'easy',m:1,e:"Shortest Path (SSSP via Dijkstra/Bellman-Ford) is in P. TSP, Subset Sum, 3-SAT are NP-complete.",y:2023,sub:'Algorithms',top:'Complexity',st:'cs'},
{q:"Quick Sort best pivot choice for guaranteed O(n log n):",opts:["First element","Random element","Median of medians","Last element"],ans:2,d:'hard',m:2,e:"Median-of-medians gives guaranteed O(n log n) worst case. Randomized gives expected O(n log n).",y:2023,sub:'Algorithms',top:'Sorting',st:'cs'},
{q:"By Master Theorem, T(n) = 2T(n/2) + n evaluates to:",opts:["O(n)","O(n log n)","O(n²)","O(log n)"],ans:1,d:'medium',m:2,e:"a=2, b=2, f(n)=n. n^log₂2 = n = f(n) → Case 2 → O(n log n).",y:2023,sub:'Algorithms',top:'Recurrences',st:'cs'},
{q:"Floyd-Warshall time complexity:",opts:["O(V²)","O(V³)","O(V² log V)","O(VE)"],ans:1,d:'easy',m:1,e:"Three nested loops each up to V → O(V³).",y:2022,sub:'Algorithms',top:'Shortest Paths',st:'cs'},
{q:"NP-complete problem means:",opts:["Cannot be solved","In NP and NP-hard","Solved in polynomial time","Not in NP"],ans:1,d:'medium',m:2,e:"NP-complete = member of NP AND NP-hard (every NP problem poly-reduces to it).",y:2022,sub:'Algorithms',top:'Complexity',st:'cs'},
{q:"Optimal substructure property is essential for:",opts:["Greedy algorithms only","Dynamic programming only","Both DP and Greedy","Backtracking"],ans:2,d:'medium',m:2,e:"Both DP and Greedy rely on optimal substructure. DP also needs overlapping subproblems.",y:2022,sub:'Algorithms',top:'Dynamic Programming',st:'cs'},
{q:"Bellman-Ford detects negative cycles because:",opts:["It uses BFS","After V−1 relaxations, any further relaxation indicates a cycle","It's O(VE)","It uses DP"],ans:1,d:'medium',m:2,e:"After V−1 iterations, shortest paths finalized. Extra relaxation → negative cycle exists.",y:2021,sub:'Algorithms',top:'Shortest Paths',st:'cs'},
{q:"Longest Common Subsequence of 'ABCBDAB' and 'BDCABA' has length:",opts:["3","4","5","6"],ans:1,d:'hard',m:2,e:"LCS = 'BCBA' or 'BDAB' → length 4.",y:2021,sub:'Algorithms',top:'Dynamic Programming',st:'cs'},
{q:"Activity selection problem is solved optimally by:",opts:["DP","Backtracking","Greedy (earliest finish time)","Branch and bound"],ans:2,d:'medium',m:1,e:"Greedy: always select the activity with earliest finish time — proven optimal.",y:2021,sub:'Algorithms',top:'Greedy',st:'cs'},
{q:"Space complexity of recursive DFS on a graph with V vertices and E edges:",opts:["O(V+E)","O(V)","O(E)","O(V²)"],ans:1,d:'medium',m:2,e:"DFS call stack depth = O(V) in worst case (path graph). Visited array = O(V).",y:2020,sub:'Algorithms',top:'Graph Algorithms',st:'cs'},
{q:"0/1 Knapsack DP solution time for n items and capacity W:",opts:["O(n+W)","O(nW)","O(n²W)","O(n log W)"],ans:1,d:'medium',m:2,e:"DP table n×W, each cell O(1) → O(nW).",y:2020,sub:'Algorithms',top:'Dynamic Programming',st:'cs'},
{q:"Kruskal's algorithm sorts edges. What's total time?",opts:["O(E log V)","O(E log E)","O(V²)","O(VE)"],ans:1,d:'medium',m:2,e:"Sort: O(E log E). Union-Find: O(E α(V)). Since log E ≈ log V², dominant is O(E log E).",y:2020,sub:'Algorithms',top:'MST',st:'cs'},
{q:"Which problem is NOT NP-complete?",opts:["3-SAT","Hamiltonian Cycle","Minimum Spanning Tree","Graph Coloring (k≥3)"],ans:2,d:'medium',m:2,e:"MST is in P (Prim's/Kruskal's). Others are NP-complete.",y:2019,sub:'Algorithms',top:'Complexity',st:'cs'},
{q:"Tower of Hanoi with n disks: minimum moves needed:",opts:["n","n²","2^n","2^n−1"],ans:3,d:'easy',m:1,e:"Recurrence T(n) = 2T(n-1)+1 → T(n) = 2^n−1.",y:2019,sub:'Algorithms',top:'Recurrences',st:'cs'},
{q:"Amortized cost of push in dynamic array doubling strategy:",opts:["O(n)","O(1)","O(log n)","O(n²)"],ans:1,d:'medium',m:2,e:"Aggregated: n pushes cost O(2n)=O(n) total → O(1) amortized per push.",y:2018,sub:'Algorithms',top:'Amortized Analysis',st:'cs'},
{q:"Which is a greedy algorithm?",opts:["Merge Sort","Dijkstra's","Floyd-Warshall","Matrix Chain Multiplication"],ans:1,d:'easy',m:1,e:"Dijkstra greedily picks minimum distance unvisited vertex each step.",y:2018,sub:'Algorithms',top:'Greedy',st:'cs'},
{q:"Maximum flow problem can be solved by:",opts:["Dijkstra","BFS","Ford-Fulkerson","DFS only"],ans:2,d:'medium',m:1,e:"Ford-Fulkerson (augmenting paths) or Edmonds-Karp (BFS-based) solve max flow.",y:2017,sub:'Algorithms',top:'Graph Algorithms',st:'cs'},
{q:"T(n) = 3T(n/4) + n² by Master Theorem:",opts:["O(n log n)","O(n²)","O(n^1.5)","O(n² log n)"],ans:1,d:'hard',m:2,e:"n^log₄3 ≈ n^0.79 << n² → Case 3 → O(n²).",y:2017,sub:'Algorithms',top:'Recurrences',st:'cs'},
{q:"String matching: KMP preprocessing builds the failure function in:",opts:["O(m)","O(m²)","O(mn)","O(m log m)"],ans:0,d:'medium',m:2,e:"KMP failure function built in O(m) by careful pointer management.",y:2016,sub:'Algorithms',top:'String Algorithms',st:'cs'},
{q:"Number of comparisons in binary search on n elements (worst case):",opts:["n","n/2","⌊log₂n⌋+1","2 log n"],ans:2,d:'easy',m:1,e:"Each step: halve. Worst case: ⌊log₂n⌋+1 comparisons.",y:2016,sub:'Algorithms',top:'Searching',st:'cs'},
{q:"Coin change: minimum coins for amount A with denominations. DP vs Greedy?",opts:["Greedy always optimal","DP always finds optimal","Same time complexity","DP uses more space"],ans:1,d:'medium',m:2,e:"DP finds optimal for any denomination set. Greedy only works for canonical systems (e.g., US coins).",y:2015,sub:'Algorithms',top:'Dynamic Programming',st:'cs'},

// OPERATING SYSTEMS — 2010-2024
{q:"FIFO page replacement suffers from Belady's anomaly because:",opts:["It's LRU","More frames can cause more faults","It uses stack property","It's random"],ans:1,d:'medium',m:1,e:"FIFO: more page frames can cause MORE faults — violates expected behavior.",y:2024,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"Semaphore initialized to 1 acts as a:",opts:["Counting semaphore","Binary semaphore/mutex","Spinlock","Monitor"],ans:1,d:'easy',m:1,e:"Binary semaphore (values 0/1) initialized to 1 provides mutual exclusion.",y:2024,sub:'Operating Systems',top:'Synchronization',st:'cs'},
{q:"In Banker's algorithm, a state is SAFE if:",opts:["No process is waiting","A safe sequence exists","All resources are free","No deadlock has occurred"],ans:1,d:'medium',m:2,e:"Safe state: at least one sequence where all processes can complete.",y:2024,sub:'Operating Systems',top:'Deadlocks',st:'cs'},
{q:"Round Robin with time quantum q and n processes: context switches per cycle:",opts:["n","n−1","n+1","2n"],ans:0,d:'easy',m:1,e:"Each of the n processes gets one turn per cycle = n context switches.",y:2023,sub:'Operating Systems',top:'CPU Scheduling',st:'cs'},
{q:"Peterson's solution to critical section assumes:",opts:["Hardware support","Only 2 processes","Priority","Semaphores"],ans:1,d:'medium',m:1,e:"Peterson's algorithm is for exactly 2 processes; generalizations exist but original is 2-process.",y:2023,sub:'Operating Systems',top:'Synchronization',st:'cs'},
{q:"Thrashing in virtual memory occurs when:",opts:["CPU utilization is 100%","Page fault rate is very high, CPU mostly doing I/O","Too many processes","Cache is full"],ans:1,d:'medium',m:2,e:"Thrashing: process spends more time swapping pages than executing — working set > RAM.",y:2023,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"Internal fragmentation occurs in which allocation?",opts:["Segmentation","Paging","Best fit","First fit"],ans:1,d:'medium',m:2,e:"Paging: last page may not be fully used → wasted space inside = internal fragmentation.",y:2022,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"Shortest Remaining Time (SRT) is:",opts:["Non-preemptive SJF","Preemptive SJF","Non-preemptive priority","Round Robin variant"],ans:1,d:'easy',m:1,e:"SRT = Preemptive SJF: preempts current process if new process has shorter remaining burst.",y:2022,sub:'Operating Systems',top:'CPU Scheduling',st:'cs'},
{q:"Which deadlock condition can be eliminated by pre-emptive allocation?",opts:["Mutual Exclusion","Hold and Wait","No Preemption","Circular Wait"],ans:2,d:'medium',m:2,e:"Breaking 'No Preemption': resources can be forcibly taken away.",y:2022,sub:'Operating Systems',top:'Deadlocks',st:'cs'},
{q:"Virtual memory allows execution of processes larger than:",opts:["Cache","RAM","Secondary storage","CPU registers"],ans:1,d:'easy',m:1,e:"Virtual memory abstracts physical RAM: process can be larger than available physical memory.",y:2021,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"The PCB (Process Control Block) contains:",opts:["Only CPU registers","Process ID, state, registers, PC, memory info","Only memory map","Scheduling info only"],ans:1,d:'easy',m:1,e:"PCB stores: PID, process state, program counter, CPU registers, memory limits, I/O info.",y:2021,sub:'Operating Systems',top:'Process Management',st:'cs'},
{q:"Optimal page replacement replaces the page that:",opts:["Was used longest ago","Will not be used for longest time in future","Is smallest","Is most recently used"],ans:1,d:'easy',m:1,e:"Optimal (Bélády's algorithm): replace page whose next use is farthest in future.",y:2021,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"LOOK disk scheduling algorithm is similar to SCAN but:",opts:["Goes to disk ends always","Reverses at last request not disk end","Sorts requests first","Random order"],ans:1,d:'medium',m:2,e:"LOOK: arm only goes as far as last request in each direction, not to disk end.",y:2020,sub:'Operating Systems',top:'Disk Scheduling',st:'cs'},
{q:"Monitor provides mutual exclusion because:",opts:["Uses semaphores internally","Only one process active inside at a time (implicitly)","Uses hardware","Uses spinlocks"],ans:1,d:'medium',m:2,e:"Monitor: only one process executes in the monitor at any time — built-in mutex.",y:2020,sub:'Operating Systems',top:'Synchronization',st:'cs'},
{q:"Spooling is used primarily for:",opts:["CPU scheduling","Slow I/O devices like printers","Memory allocation","Disk caching"],ans:1,d:'easy',m:1,e:"Spooling (Simultaneous Peripheral Operations OnLine): buffers I/O for slow devices.",y:2019,sub:'Operating Systems',top:'I/O Management',st:'cs'},
{q:"In a system with 3 processes and max 2 resources each, minimum resources to guarantee no deadlock:",opts:["4","5","6","7"],ans:1,d:'hard',m:2,e:"Deadlock possible only if each process holds 1 and waits for 1 more. Need (max-1)×n + 1 = 1×3+1=4? No: guarantee = n(k-1)+1 = 3(1)+1 = 4. But wait: each holds 1 = 3 resources, need at least 4.",y:2019,sub:'Operating Systems',top:'Deadlocks',st:'cs'},
{q:"Context switching overhead involves:",opts:["I/O operations","Saving/restoring PCB (registers, PC, SP)","Memory allocation","Interrupt vectoring"],ans:1,d:'easy',m:1,e:"Context switch: save current PCB (all registers, PC, stack pointer), load next process's PCB.",y:2018,sub:'Operating Systems',top:'Process Management',st:'cs'},
{q:"Page table entry contains page frame number and bits for:",opts:["Priority","Valid/invalid, dirty, reference bits","Process ID","File name"],ans:1,d:'medium',m:2,e:"PTE: frame number + valid bit (in memory?), dirty bit (modified?), reference bit (accessed?).",y:2018,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"CPU utilization in multiprogramming vs uniprogramming: multiprogramming is better because:",opts:["Faster CPU","CPU used during I/O waits of other processes","Less context switching","Hardware support"],ans:1,d:'easy',m:1,e:"Multiprogramming: while one process waits for I/O, another runs → higher CPU utilization.",y:2017,sub:'Operating Systems',top:'Process Management',st:'cs'},
{q:"Which scheduling algorithm is best for interactive time-sharing systems?",opts:["FCFS","SJF","Round Robin","Priority non-preemptive"],ans:2,d:'easy',m:1,e:"Round Robin: each process gets equal time slice → fair, good response time for interactive use.",y:2016,sub:'Operating Systems',top:'CPU Scheduling',st:'cs'},

// DBMS — 2010-2024
{q:"3NF (Third Normal Form) allows which dependency?",opts:["Partial dependencies","Transitive via non-prime if determinant is a candidate key","Multivalued dependencies","Partial + transitive"],ans:1,d:'hard',m:2,e:"3NF: non-prime may transitively depend on non-prime IF that non-prime is a candidate key.",y:2024,sub:'DBMS',top:'Normal Forms',st:'cs'},
{q:"Which SQL isolation level prevents dirty reads but allows non-repeatable reads?",opts:["Read Uncommitted","Read Committed","Repeatable Read","Serializable"],ans:1,d:'medium',m:2,e:"Read Committed: only committed data read → no dirty reads; but another transaction may update between reads.",y:2024,sub:'DBMS',top:'Transactions',st:'cs'},
{q:"Second maximum salary using SQL:",opts:["SELECT MAX(salary) WHERE salary<MAX(salary)","SELECT MAX(salary) FROM emp WHERE salary<(SELECT MAX(salary) FROM emp)","SELECT DISTINCT salary ORDER BY DESC LIMIT 2","SELECT salary RANK()=2"],ans:1,d:'hard',m:2,e:"Subquery finds max; outer WHERE filters below max then MAX gives 2nd highest.",y:2024,sub:'DBMS',top:'SQL',st:'cs'},
{q:"B+ tree advantage over B-tree:",opts:["B+ tree is faster for point queries","All data at leaf level + linked leaves enable range scans","B+ tree is shorter","Uses less space"],ans:1,d:'medium',m:2,e:"B+ tree: all records at leaves, leaves linked → sequential range scans O(n) instead of tree traversal.",y:2023,sub:'DBMS',top:'Indexing',st:'cs'},
{q:"ACID property 'Atomicity' means:",opts:["Transaction either fully completes or fully aborts","All transactions execute concurrently","Isolation from other transactions","Data persists after commit"],ans:0,d:'easy',m:1,e:"Atomicity: transaction is all-or-nothing — no partial execution visible.",y:2023,sub:'DBMS',top:'Transactions',st:'cs'},
{q:"Deadlock in DBMS prevented by:",opts:["Two-phase locking","Wait-die and Wound-wait (timestamp ordering)","MVCC","Log-based recovery"],ans:1,d:'hard',m:2,e:"Wait-Die: older waits for younger (or dies). Wound-Wait: older wounds (preempts) younger. Both prevent circular wait.",y:2023,sub:'DBMS',top:'Concurrency Control',st:'cs'},
{q:"Relational algebra — Natural Join of R(A,B,C) and S(B,C,D) projects on:",opts:["All distinct attributes: A,B,C,D","A,B,C,D,B,C","Only A,D","B,C only"],ans:0,d:'medium',m:2,e:"Natural join: join on common attributes B,C, result schema = all distinct = A,B,C,D.",y:2022,sub:'DBMS',top:'Relational Algebra',st:'cs'},
{q:"Which is NOT a DDL command?",opts:["CREATE","ALTER","INSERT","DROP"],ans:2,d:'easy',m:1,e:"INSERT is DML (Data Manipulation Language). CREATE, ALTER, DROP are DDL.",y:2022,sub:'DBMS',top:'SQL',st:'cs'},
{q:"BCNF (Boyce-Codd) is stricter than 3NF because:",opts:["No multivalued deps","Every determinant must be a superkey (no exceptions)","Allows all functional deps","Only atomic values"],ans:1,d:'medium',m:2,e:"BCNF: for every FD X→Y, X must be a superkey. 3NF allows exceptions for prime attributes.",y:2022,sub:'DBMS',top:'Normal Forms',st:'cs'},
{q:"Checkpoint in database recovery helps by:",opts:["Preventing deadlocks","Reducing redo work after crash","Encrypting data","Removing old transactions"],ans:1,d:'medium',m:2,e:"Checkpoint: flushes dirty pages, records to log → crash recovery only redoes work after last checkpoint.",y:2021,sub:'DBMS',top:'Recovery',st:'cs'},
{q:"Foreign key constraint enforces:",opts:["Uniqueness","Referential integrity","Primary key","Not null"],ans:1,d:'easy',m:1,e:"Foreign key: value must exist in referenced table (or be NULL) → referential integrity.",y:2021,sub:'DBMS',top:'Constraints',st:'cs'},
{q:"Two-phase locking (2PL) guarantees:",opts:["Deadlock freedom","Serializability","Both","Neither"],ans:1,d:'medium',m:2,e:"2PL ensures conflict-serializability. It does NOT prevent deadlocks.",y:2020,sub:'DBMS',top:'Concurrency Control',st:'cs'},
{q:"Which normal form eliminates multivalued dependencies?",opts:["1NF","2NF","3NF","4NF"],ans:3,d:'medium',m:2,e:"4NF: eliminates non-trivial multivalued dependencies where determinant is not a superkey.",y:2020,sub:'DBMS',top:'Normal Forms',st:'cs'},
{q:"In ER diagram, double rectangle represents:",opts:["Strong entity","Weak entity","Relationship","Derived attribute"],ans:1,d:'easy',m:1,e:"Weak entity set drawn with double rectangle — depends on identifying relationship.",y:2019,sub:'DBMS',top:'ER Model',st:'cs'},
{q:"Hash-based join is efficient when:",opts:["Tables are sorted","Tables fit in memory (or hash fits)","Indices exist","Tables are skewed"],ans:1,d:'medium',m:2,e:"Hash join partitions on join attribute; if hash fits in memory → efficient for equi-joins.",y:2018,sub:'DBMS',top:'Query Processing',st:'cs'},

// COMPUTER NETWORKS — 2010-2024
{q:"Subnetting 192.168.1.0/24 into /26 gives how many subnets?",opts:["2","4","8","16"],ans:1,d:'medium',m:2,e:"/24 to /26: borrow 2 bits → 2² = 4 subnets each with 64 addresses.",y:2024,sub:'Computer Networks',top:'Subnetting',st:'cs'},
{q:"TCP three-way handshake order:",opts:["SYN, ACK, SYN-ACK","SYN, SYN-ACK, ACK","ACK, SYN, SYN-ACK","SYN-ACK, SYN, ACK"],ans:1,d:'easy',m:1,e:"Client→SYN, Server→SYN-ACK, Client→ACK. Three-way handshake establishes connection.",y:2024,sub:'Computer Networks',top:'TCP/IP',st:'cs'},
{q:"HTTPS uses port:",opts:["80","8080","443","22"],ans:2,d:'easy',m:1,e:"HTTPS = HTTP + TLS/SSL. Default port 443.",y:2023,sub:'Computer Networks',top:'Application Layer',st:'cs'},
{q:"OSPF routing protocol uses which algorithm?",opts:["Bellman-Ford","Dijkstra's SPF","Distance vector","Count to infinity"],ans:1,d:'medium',m:2,e:"OSPF is link-state: each router maintains full topology map, runs Dijkstra's SPF locally.",y:2023,sub:'Computer Networks',top:'Routing',st:'cs'},
{q:"Sliding window protocol window size 2^n - 1 for:",opts:["Go-Back-N","Selective Repeat","Stop-and-Wait","Both SR and GBN"],ans:0,d:'hard',m:2,e:"Go-Back-N: window = 2^n−1. Selective Repeat: window = 2^(n-1). For n-bit sequence number.",y:2023,sub:'Computer Networks',top:'Data Link Layer',st:'cs'},
{q:"ARP resolves:",opts:["IP to MAC address","MAC to IP address","Domain to IP","IP to port"],ans:0,d:'easy',m:1,e:"ARP (Address Resolution Protocol): given IP address, find corresponding MAC address.",y:2022,sub:'Computer Networks',top:'Network Layer',st:'cs'},
{q:"Which layer of OSI provides logical addressing?",opts:["Physical","Data Link","Network","Transport"],ans:2,d:'easy',m:1,e:"Network Layer (Layer 3): IP addressing, routing, fragmentation.",y:2022,sub:'Computer Networks',top:'OSI Model',st:'cs'},
{q:"Pure ALOHA maximum throughput:",opts:["50%","36.8%","18.4%","25%"],ans:2,d:'hard',m:2,e:"Pure ALOHA: S = G×e^(−2G), max at G=0.5: S = 1/(2e) ≈ 18.4%.",y:2022,sub:'Computer Networks',top:'MAC Protocols',st:'cs'},
{q:"DNS uses which transport protocol primarily?",opts:["TCP port 53","UDP port 53","ICMP","Both TCP and UDP port 53"],ans:3,d:'medium',m:2,e:"DNS uses UDP port 53 (fast queries), TCP port 53 (zone transfers / large responses).",y:2021,sub:'Computer Networks',top:'Application Layer',st:'cs'},
{q:"IPv6 address size:",opts:["32 bits","64 bits","128 bits","256 bits"],ans:2,d:'easy',m:1,e:"IPv6: 128 bits = 16 bytes written as 8 groups of 4 hex digits.",y:2021,sub:'Computer Networks',top:'IP Addressing',st:'cs'},
{q:"CRC polynomial division detects all burst errors of length:",opts:["Exactly 1","≤ degree of generator polynomial","All odd errors","None"],ans:1,d:'hard',m:2,e:"CRC with degree-r polynomial detects all burst errors ≤ r bits in length.",y:2020,sub:'Computer Networks',top:'Error Detection',st:'cs'},
{q:"Token Ring is a:",opts:["Bus topology with CSMA/CD","Ring topology with token passing","Star topology","Mesh topology"],ans:1,d:'easy',m:1,e:"Token Ring: stations in ring; possession of token grants right to transmit.",y:2019,sub:'Computer Networks',top:'Data Link Layer',st:'cs'},
{q:"BGP is a:",opts:["Intra-domain routing protocol","Inter-domain (exterior gateway) protocol","Link-state protocol","Distance vector intra-domain"],ans:1,d:'medium',m:2,e:"BGP (Border Gateway Protocol): exterior gateway protocol used between autonomous systems on Internet.",y:2018,sub:'Computer Networks',top:'Routing',st:'cs'},
{q:"RSA encryption: which key is used to decrypt?",opts:["Same key (symmetric)","Private key","Public key","Session key"],ans:1,d:'easy',m:1,e:"RSA: encrypt with recipient's public key → decrypt with recipient's private key.",y:2017,sub:'Computer Networks',top:'Security',st:'cs'},
{q:"Bandwidth-delay product represents:",opts:["Latency only","Bits in transit in the network pipe","Throughput","RTT"],ans:1,d:'medium',m:2,e:"BDP = bandwidth × RTT = bits 'in flight' (filling the pipe) at any time.",y:2016,sub:'Computer Networks',top:'Performance',st:'cs'},

// THEORY OF COMPUTATION — 2010-2024
{q:"Language {aⁿbⁿcⁿ | n≥1} is:",opts:["Regular","Context-Free","Context-Sensitive","Recursive Enumerable only"],ans:2,d:'medium',m:2,e:"Requires matching 3 counts → beyond CFL. Accepted by LBA = CSL.",y:2024,sub:'Theory of Computation',top:'Language Classes',st:'cs'},
{q:"Converting NFA with n states to DFA: maximum states in DFA:",opts:["n","n²","2n","2^n"],ans:3,d:'medium',m:2,e:"Subset construction: each DFA state = subset of NFA states → 2^n states worst case.",y:2024,sub:'Theory of Computation',top:'Automata',st:'cs'},
{q:"Regular expression r* denotes:",opts:["r repeated exactly once","r repeated zero or more times","r repeated one or more times","Empty language"],ans:1,d:'easy',m:1,e:"Kleene star: zero or more repetitions of r, including empty string ε.",y:2023,sub:'Theory of Computation',top:'Regular Expressions',st:'cs'},
{q:"Which language is NOT regular?",opts:["{a^n | n is prime}","{ab}*","(a|b)*abb","a*b*"],ans:0,d:'medium',m:2,e:"{a^n | n prime}: cannot be described by finite automaton — primes have no regular pattern.",y:2023,sub:'Theory of Computation',top:'Regular Languages',st:'cs'},
{q:"'Does TM M halt on input w?' is:",opts:["Decidable","Semi-decidable (RE but not recursive)","Not even RE","Context-sensitive"],ans:1,d:'medium',m:2,e:"Halting problem: semi-decidable (TM accepts if M halts, loops otherwise) — not decidable.",y:2023,sub:'Theory of Computation',top:'Decidability',st:'cs'},
{q:"DPDA (Deterministic PDA) accepts exactly:",opts:["All CFL","DCFL (Deterministic CFL)","Regular languages","Recursive languages"],ans:1,d:'hard',m:2,e:"DPDA recognizes DCFL — a proper subset of CFL (e.g., palindromes are CFL but not DCFL).",y:2022,sub:'Theory of Computation',top:'Pushdown Automata',st:'cs'},
{q:"CFL is NOT closed under:",opts:["Union","Concatenation","Kleene Star","Intersection"],ans:3,d:'medium',m:2,e:"CFL ∩ CFL need not be CFL. Example: {aⁿbⁿcⁿ} = {aⁿbⁿ} ∩ {bⁿcⁿ}.",y:2022,sub:'Theory of Computation',top:'Closure Properties',st:'cs'},
{q:"Turing machine with 2-way infinite tape is equivalent to:",opts:["Standard TM","TM with 2 tapes","FA","PDA"],ans:0,d:'medium',m:2,e:"TM with 2-way infinite tape: same power as standard 1-way infinite TM — simulate by folding.",y:2021,sub:'Theory of Computation',top:'Turing Machines',st:'cs'},
{q:"Pumping lemma for regular languages states: for string |w|≥p, we can write w=xyz where:",opts:["|xy|≤p, |y|≥1","xy^iz∈L for all i≥0","Both A and B","Only |y|≥1"],ans:2,d:'hard',m:2,e:"Both conditions needed: |xy|≤p (pump in first p chars), |y|≥1 (non-empty pump), xy^iz∈L ∀i≥0.",y:2021,sub:'Theory of Computation',top:'Regular Languages',st:'cs'},
{q:"A grammar is ambiguous if some string has:",opts:["Two different meanings","Two different parse trees (leftmost)","ε-productions","Left recursion"],ans:1,d:'medium',m:1,e:"Ambiguous: same string has two distinct leftmost derivations / parse trees.",y:2020,sub:'Theory of Computation',top:'Context-Free Grammars',st:'cs'},
{q:"Rice's theorem states: all non-trivial semantic properties of TMs are:",opts:["Decidable","Undecidable","Semi-decidable","Context-sensitive"],ans:1,d:'hard',m:2,e:"Rice's theorem: every non-trivial property of the language recognized by a TM is undecidable.",y:2019,sub:'Theory of Computation',top:'Decidability',st:'cs'},
{q:"Number of states in minimal DFA for L = {w | w ends with 01}:",opts:["2","3","4","5"],ans:1,d:'hard',m:2,e:"Need 3 states: q0 (start), q1 (saw 0), q2 (saw 01, accept). Cannot merge any.",y:2018,sub:'Theory of Computation',top:'Automata',st:'cs'},

// COMPUTER ORGANIZATION — 2010-2024
{q:"IEEE 754 single precision: exponent bits and mantissa bits:",opts:["7, 24","8, 23","7, 25","10, 21"],ans:1,d:'medium',m:2,e:"IEEE 754 single: 1 sign + 8 exponent (biased 127) + 23 mantissa = 32 bits.",y:2024,sub:'Computer Organization',top:'Number Systems',st:'cs'},
{q:"Direct mapped cache hit time vs main memory miss: cache speedup relies on:",opts:["Large cache size","Locality of reference","Multiple cores","Pipelining"],ans:1,d:'medium',m:1,e:"Cache effectiveness relies on temporal and spatial locality of memory accesses.",y:2024,sub:'Computer Organization',top:'Cache Memory',st:'cs'},
{q:"Pipeline hazard that requires stalling:",opts:["Structural hazard","Data hazard (RAW)","Control hazard","All of the above"],ans:3,d:'medium',m:2,e:"All three types can cause stalls. RAW data hazards most common; forwarding reduces them.",y:2023,sub:'Computer Organization',top:'Pipelining',st:'cs'},
{q:"Which addressing mode is used in: MOV R1, [R2+100]?",opts:["Register","Immediate","Base+Displacement","Indirect"],ans:2,d:'easy',m:1,e:"Base+displacement: effective address = R2 + 100. Used for accessing struct fields / arrays.",y:2023,sub:'Computer Organization',top:'Addressing Modes',st:'cs'},
{q:"Cache write policy that writes to both cache and memory simultaneously:",opts:["Write-back","Write-through","Write-allocate","No-write-allocate"],ans:1,d:'easy',m:1,e:"Write-through: every write goes to both cache and main memory — simple, always consistent.",y:2022,sub:'Computer Organization',top:'Cache Memory',st:'cs'},
{q:"RISC vs CISC: RISC advantage is:",opts:["More instructions","Complex instructions","Fixed instruction size, single-cycle (mostly)","Larger programs"],ans:2,d:'easy',m:1,e:"RISC: fixed-size instructions, load-store architecture → simpler pipeline, higher clock speed.",y:2022,sub:'Computer Organization',top:'CPU Architecture',st:'cs'},
{q:"For a 4-stage pipeline, if each stage takes 1ns, throughput for n instructions:",opts:["n/4 ns","n + 3 ns","4n ns","n ns"],ans:1,d:'hard',m:2,e:"Fill pipeline: first instruction takes 4 cycles, then 1 per cycle. Total = n + (k-1) cycles = n + 3 ns.",y:2021,sub:'Computer Organization',top:'Pipelining',st:'cs'},
{q:"DMA (Direct Memory Access) is used to:",opts:["Execute faster programs","Transfer data between I/O and memory without CPU","Cache main memory","Handle interrupts"],ans:1,d:'easy',m:1,e:"DMA: I/O controller transfers data directly to/from memory, freeing CPU for other tasks.",y:2020,sub:'Computer Organization',top:'I/O',st:'cs'},
{q:"Two's complement of 8-bit 1000 0000 is:",opts:["0000 0000","1000 0000","0111 1111","1111 1111"],ans:1,d:'hard',m:2,e:"-128 (min value for 8-bit): 1000 0000 → negate: flip = 0111 1111, +1 = 1000 0000. Self-inverse!",y:2019,sub:'Computer Organization',top:'Number Systems',st:'cs'},
{q:"Cache miss penalty is high; effective memory access time = h×Tc + (1-h)×Tm. If h=0.9, Tc=10ns, Tm=100ns:",opts:["10ns","19ns","55ns","100ns"],ans:1,d:'medium',m:2,e:"0.9×10 + 0.1×100 = 9 + 10 = 19 ns.",y:2018,sub:'Computer Organization',top:'Cache Memory',st:'cs'},

// ECE — SIGNALS & SYSTEMS
{q:"Fourier series of odd function has only:",opts:["Cosine terms","Sine terms","Both","DC only"],ans:1,d:'easy',m:1,e:"Odd function: f(-t) = -f(t). Cosines are even → coefficient = 0. Only sines remain.",y:2024,sub:'Signals & Systems',top:'Fourier Series',st:'ece'},
{q:"LTI system is BIBO stable if and only if:",opts:["H(jω) is bounded","Impulse response h(t) is absolutely integrable","Poles in left half-plane (continuous)","All of the above"],ans:3,d:'medium',m:2,e:"All conditions are equivalent for LTI: ∫|h(t)|dt < ∞, poles in LHP (CT), inside unit circle (DT).",y:2024,sub:'Signals & Systems',top:'System Properties',st:'ece'},
{q:"Z-transform of u[n] (unit step) is:",opts:["1/(z-1) for |z|>1","z/(z-1) for |z|>1","1/z","z"],ans:1,d:'medium',m:2,e:"Z{u[n]} = Σ z^(-n) for n≥0 = 1/(1-z^(-1)) = z/(z-1), ROC |z|>1.",y:2023,sub:'Signals & Systems',top:'Z-Transform',st:'ece'},
{q:"Nyquist sampling theorem: minimum sampling rate for signal with max frequency fm:",opts:["fm","fm/2","2fm","4fm"],ans:2,d:'easy',m:1,e:"Nyquist rate = 2×fm (twice the highest frequency). Sampling below causes aliasing.",y:2023,sub:'Signals & Systems',top:'Sampling',st:'ece'},
{q:"Convolution of two rectangular pulses of width T gives:",opts:["Rectangular pulse","Triangular pulse of width 2T","Impulse","Exponential"],ans:1,d:'medium',m:2,e:"Rect * Rect = Triangle. Width doubles (2T), height = T. Seen in FT: sinc² shape.",y:2022,sub:'Signals & Systems',top:'Convolution',st:'ece'},
{q:"Laplace transform of e^(-at)u(t):",opts:["1/(s+a) Re(s)>-a","1/(s-a)","a/s²","1/s"],ans:0,d:'easy',m:1,e:"L{e^(-at)u(t)} = 1/(s+a), ROC: Re(s) > -a.",y:2022,sub:'Signals & Systems',top:'Laplace Transform',st:'ece'},
{q:"DFT of length-N real sequence has conjugate symmetry: X[k] = X*[N-k]. Independent real values:",opts:["N/2","N/2+1","N","2N"],ans:1,d:'hard',m:2,e:"Real DFT symmetry: X[k]=X*[N-k]. Independent = N/2+1 complex = N/2+1 independent real values.",y:2021,sub:'Signals & Systems',top:'DFT',st:'ece'},
{q:"Parseval's theorem for DTFT:",opts:["Energy in time = energy in frequency (with 1/2π)","Power = amplitude squared","Energy = sum of squares","All signals have same energy"],ans:0,d:'medium',m:2,e:"Parseval (DTFT): Σ|x[n]|² = (1/2π)∫|X(e^jω)|²dω — energy conservation.",y:2020,sub:'Signals & Systems',top:'DTFT',st:'ece'},
{q:"Group delay of an LTI system = −dφ(ω)/dω. Linear phase means:",opts:["Zero group delay","Constant group delay","Infinite group delay","Frequency-dependent group delay"],ans:1,d:'hard',m:2,e:"Linear phase: φ(ω) = −αω → group delay = −d(−αω)/dω = α = constant. No dispersion.",y:2019,sub:'Signals & Systems',top:'Frequency Response',st:'ece'},

// ECE — ELECTRONIC DEVICES
{q:"In a pn-junction, depletion region forms due to:",opts:["Excess carriers","Diffusion creating fixed charges","Applied voltage","Thermal excitation"],ans:1,d:'easy',m:1,e:"Diffusion of electrons/holes leaves behind fixed donor/acceptor ions → depletion region.",y:2024,sub:'Electronic Devices',top:'PN Junction',st:'ece'},
{q:"For MOSFET in saturation region, drain current ID ∝:",opts:["VGS","VDS","(VGS−Vth)²","VGS−VDS"],ans:2,d:'medium',m:2,e:"MOSFET saturation: ID = (μCox W/2L)(VGS−Vth)² — square-law dependence.",y:2024,sub:'Electronic Devices',top:'MOSFETs',st:'ece'},
{q:"Zener diode is used in:",opts:["Amplification","Voltage regulation (reverse breakdown)","Rectification","Oscillation"],ans:1,d:'easy',m:1,e:"Zener: operates in reverse breakdown at specific Vz — used for voltage regulation.",y:2023,sub:'Electronic Devices',top:'Diodes',st:'ece'},
{q:"BJT in saturation region: both junctions are:",opts:["Forward biased","Reverse biased","Emitter forward, collector reverse","Both reversed"],ans:0,d:'medium',m:2,e:"BJT saturation: both emitter-base AND collector-base junctions forward biased.",y:2023,sub:'Electronic Devices',top:'BJTs',st:'ece'},
{q:"Threshold voltage VT of MOSFET shifts negative when:",opts:["P-type substrate","Positive oxide charge (Qox)","Thicker oxide","More doping"],ans:1,d:'hard',m:2,e:"Positive fixed oxide charge Qox reduces VT (requires less gate voltage to invert).",y:2022,sub:'Electronic Devices',top:'MOSFETs',st:'ece'},

// ME — THERMODYNAMICS
{q:"For an ideal gas, internal energy depends only on:",opts:["Pressure","Volume","Temperature","Entropy"],ans:2,d:'easy',m:1,e:"Joule's law: ideal gas internal energy is function of temperature only (not P or V).",y:2024,sub:'Thermodynamics',top:'Ideal Gas',st:'me'},
{q:"Carnot efficiency of engine between TH=600K and TL=300K:",opts:["25%","50%","75%","100%"],ans:1,d:'easy',m:1,e:"η_Carnot = 1 − TL/TH = 1 − 300/600 = 0.5 = 50%.",y:2024,sub:'Thermodynamics',top:'Carnot Cycle',st:'me'},
{q:"Entropy change of universe for irreversible process:",opts:["Zero","Negative","Positive","Undefined"],ans:2,d:'easy',m:1,e:"Second law: ΔS_universe > 0 for irreversible, = 0 for reversible.",y:2023,sub:'Thermodynamics',top:'Second Law',st:'me'},
{q:"Rankine cycle efficiency improves by superheating because:",opts:["Increases condenser pressure","Increases mean temperature of heat addition","Reduces boiler pressure","Reduces entropy"],ans:1,d:'medium',m:2,e:"Superheating: higher mean temperature of heat addition → higher Rankine efficiency.",y:2023,sub:'Thermodynamics',top:'Rankine Cycle',st:'me'},
{q:"In throttling valve, which property remains constant?",opts:["Temperature","Entropy","Enthalpy","Pressure"],ans:2,d:'medium',m:2,e:"Throttling: steady-flow, no work, no heat → h1 = h2 (isenthalpic process).",y:2022,sub:'Thermodynamics',top:'Steady Flow Devices',st:'me'},
{q:"COP of refrigerator = QL/W. For reversed Carnot: COP =",opts:["TH/(TH−TL)","TL/(TH−TL)","TH/TL","TL/TH"],ans:1,d:'medium',m:2,e:"Reversed Carnot refrigerator: COP = TL/(TH−TL).",y:2022,sub:'Thermodynamics',top:'Refrigeration',st:'me'},
{q:"Brayton cycle efficiency = 1 − (1/rp)^((γ−1)/γ). With rp=8, γ=1.4:",opts:["40%","44.8%","50%","56%"],ans:1,d:'hard',m:2,e:"η = 1 − (1/8)^(0.4/1.4) = 1 − 0.5518 = 0.448 ≈ 44.8%.",y:2021,sub:'Thermodynamics',top:'Brayton Cycle',st:'me'},
{q:"Cp − Cv for an ideal gas equals:",opts:["0","R (universal gas constant)","Cv","Cp/γ"],ans:1,d:'easy',m:1,e:"Mayer's relation: Cp − Cv = R for ideal gas.",y:2020,sub:'Thermodynamics',top:'Ideal Gas',st:'me'},

// GENERAL APTITUDE — 2010-2024
{q:"A can complete work in 12 days, B in 18 days. Together in:",opts:["7.2 days","8 days","9 days","10 days"],ans:0,d:'medium',m:2,e:"Rate = 1/12+1/18 = 3/36+2/36 = 5/36 per day. Time = 36/5 = 7.2 days.",y:2024,sub:'Quantitative Aptitude',top:'Work & Time',st:'ga'},
{q:"Train 200m long passes a 400m bridge at 72 km/h. Time taken:",opts:["20 s","30 s","36 s","40 s"],ans:1,d:'medium',m:2,e:"Speed = 72×1000/3600 = 20 m/s. Distance = 200+400 = 600m. Time = 600/20 = 30s.",y:2024,sub:'Quantitative Aptitude',top:'Time, Speed & Distance',st:'ga'},
{q:"log₃(243) = ?",opts:["4","5","6","3"],ans:1,d:'easy',m:1,e:"3⁵ = 243. So log₃(243) = 5.",y:2023,sub:'Quantitative Aptitude',top:'Logarithms',st:'ga'},
{q:"Probability of drawing 2 red balls from bag of 4 red, 3 blue:",opts:["2/7","12/42","6/21","2/7"],ans:0,d:'medium',m:2,e:"P = C(4,2)/C(7,2) = 6/21 = 2/7.",y:2023,sub:'Quantitative Aptitude',top:'Probability',st:'ga'},
{q:"Sum of first n natural numbers = n(n+1)/2. What is 1+2+…+100?",opts:["5000","5050","4950","5100"],ans:1,d:'easy',m:1,e:"100×101/2 = 5050.",y:2022,sub:'Quantitative Aptitude',top:'Series',st:'ga'},
{q:"If A is 20% more than B, then B is what % less than A?",opts:["20%","16.67%","25%","15%"],ans:1,d:'medium',m:2,e:"B = A/1.2. Diff = A − A/1.2 = A×0.2/1.2. % less than A = (0.2/1.2)×100 = 16.67%.",y:2022,sub:'Quantitative Aptitude',top:'Percentages',st:'ga'},
{q:"All roses are flowers. Some flowers fade quickly. Therefore:",opts:["All roses fade quickly","Some roses may fade quickly","No roses fade","All flowers are roses"],ans:1,d:'medium',m:2,e:"Syllogism: cannot conclude all roses fade; only that some flowers do. Roses might or might not.",y:2021,sub:'Quantitative Aptitude',top:'Logical Reasoning',st:'ga'},
{q:"The series 2, 5, 10, 17, 26, __ next term:",opts:["35","37","36","38"],ans:1,d:'easy',m:1,e:"Differences: 3,5,7,9,11 (+2 each time). Next = 26+11 = 37.",y:2021,sub:'Quantitative Aptitude',top:'Series',st:'ga'},
{q:"Simple interest vs compound interest: for same P, R, T (T=2), CI−SI =",opts:["P(R/100)","P(R/100)²","PR/100","P²R/100"],ans:1,d:'medium',m:2,e:"For 2 years: CI−SI = P(R/100)².",y:2020,sub:'Quantitative Aptitude',top:'Interest',st:'ga'},
{q:"In a group of 100, 60 speak Hindi, 45 speak English, 25 speak both. Neither:",opts:["10","20","15","30"],ans:1,d:'medium',m:2,e:"Union = 60+45−25 = 80. Neither = 100−80 = 20.",y:2020,sub:'Quantitative Aptitude',top:'Set Theory',st:'ga'},

// ══ THEORY OF COMPUTATION ══
{q:"Which of the following is NOT a regular language?",opts:["Set of strings with equal 0s and 1s","Set of all binary strings","Set of strings ending in 01","Set of strings with at most three 1s"],ans:0,d:'medium',m:2,e:"Equal number of 0s and 1s requires counting — not regular. A DFA cannot count arbitrarily.",y:2023,sub:'Theory of Computation',top:'Regular Languages',st:'cs'},
{q:"The language L = {a^n b^n | n ≥ 1} is:",opts:["Regular","Context-free but not regular","Context-sensitive but not CFL","Recursively enumerable but not CS"],ans:1,d:'easy',m:1,e:"L = a^n b^n is the classic CFL. It requires a stack to match a's and b's — not regular.",y:2022,sub:'Theory of Computation',top:'Context Free Languages',st:'cs'},
{q:"A DFA for the language of binary strings divisible by 3 has minimum how many states?",opts:["2","3","4","6"],ans:1,d:'medium',m:2,e:"3 states representing remainders 0,1,2 mod 3. Start/accept state = remainder 0.",y:2021,sub:'Theory of Computation',top:'DFA',st:'cs'},
{q:"Which of the following problems is undecidable?",opts:["Does a DFA accept the empty string","Is a given CFG ambiguous","Does a DFA accept a finite language","Is the intersection of two DFAs empty"],ans:1,d:'hard',m:2,e:"Ambiguity of CFG is undecidable. Others (DFA acceptance, finiteness, intersection) are decidable.",y:2022,sub:'Theory of Computation',top:'Decidability',st:'cs'},
{q:"The pumping lemma for regular languages states that for any string w with |w| ≥ p, w can be split as xyz where:",opts:["y ≠ ε and |xy| ≤ p","x ≠ ε and |xy| ≤ p","y ≠ ε and |yz| ≤ p","x ≠ ε and |xz| ≤ p"],ans:0,d:'medium',m:2,e:"The pumping lemma requires: y ≠ ε (non-empty pump), |xy| ≤ p (pump near start), xy^i z ∈ L for all i ≥ 0.",y:2020,sub:'Theory of Computation',top:'Pumping Lemma',st:'cs'},
{q:"A language is accepted by a pushdown automaton if and only if it is:",opts:["Regular","Context-free","Context-sensitive","Recursive"],ans:1,d:'easy',m:1,e:"PDAs accept exactly the class of context-free languages. Regular ⊂ CFL ⊂ CSL.",y:2019,sub:'Theory of Computation',top:'Pushdown Automata',st:'cs'},
{q:"Which grammar is ambiguous? S → SS | a",opts:["It is unambiguous","Only if a appears once","It is ambiguous","Depends on start symbol"],ans:2,d:'medium',m:2,e:"S → SS | a is ambiguous: 'aaa' has two different parse trees (left vs right associativity of SS).",y:2021,sub:'Theory of Computation',top:'Context Free Grammars',st:'cs'},
{q:"The class of recursive languages is closed under:",opts:["Union only","Complement only","Both union and complement","Neither"],ans:2,d:'hard',m:2,e:"Recursive (decidable) languages are closed under union, intersection, complement, concatenation.",y:2020,sub:'Theory of Computation',top:'Decidability',st:'cs'},
{q:"NFA and DFA are equivalent in terms of:",opts:["Time complexity","Number of states","Expressive power (languages accepted)","Space complexity"],ans:2,d:'easy',m:1,e:"Every NFA has an equivalent DFA (subset construction). They accept the same class: regular languages.",y:2018,sub:'Theory of Computation',top:'DFA',st:'cs'},
{q:"Halting problem is:",opts:["Decidable","Semi-decidable (recursively enumerable)","Not even semi-decidable","Decidable for finite input"],ans:1,d:'medium',m:2,e:"Halting problem is semi-decidable (RE) — a TM can confirm halting but not confirm non-halting.",y:2023,sub:'Theory of Computation',top:'Decidability',st:'cs'},
{q:"Rice's theorem states that every non-trivial semantic property of programs is:",opts:["Decidable","Undecidable","Semi-decidable","Polynomial-time decidable"],ans:1,d:'hard',m:2,e:"Rice's theorem: any non-trivial property about the language of a TM is undecidable.",y:2022,sub:'Theory of Computation',top:'Decidability',st:'cs'},
{q:"Minimum number of states in DFA accepting strings over {0,1} that end in '01':",opts:["2","3","4","5"],ans:1,d:'medium',m:2,e:"3 states needed: q0 (start, last char not 0), q1 (last char was 0), q2 (accept: last two were 01).",y:2019,sub:'Theory of Computation',top:'DFA',st:'cs'},

// ══ DISCRETE MATHEMATICS ══
{q:"How many different binary strings of length 8 have exactly three 1s?",opts:["28","56","70","24"],ans:1,d:'easy',m:1,e:"C(8,3) = 8!/(3!×5!) = 56.",y:2023,sub:'Discrete Mathematics',top:'Combinatorics',st:'cs'},
{q:"The number of onto functions from a 5-element set to a 3-element set is:",opts:["150","180","240","125"],ans:0,d:'hard',m:2,e:"Using inclusion-exclusion: 3^5 − C(3,1)×2^5 + C(3,2)×1^5 = 243 − 96 + 3 = 150.",y:2022,sub:'Discrete Mathematics',top:'Functions & Relations',st:'cs'},
{q:"In a simple graph with n vertices, the maximum number of edges is:",opts:["n(n-1)","n(n-1)/2","n²","n(n+1)/2"],ans:1,d:'easy',m:1,e:"Complete graph K_n has n(n−1)/2 edges — each pair of vertices connected exactly once.",y:2021,sub:'Discrete Mathematics',top:'Graph Theory',st:'cs'},
{q:"Which of these is a tautology?",opts:["p ∧ ¬p","p ∨ ¬p","p → q","p ↔ q"],ans:1,d:'easy',m:1,e:"p ∨ ¬p (law of excluded middle) is always true — a tautology.",y:2020,sub:'Discrete Mathematics',top:'Propositional Logic',st:'cs'},
{q:"The chromatic number of a complete bipartite graph K_{3,3} is:",opts:["2","3","4","6"],ans:0,d:'medium',m:2,e:"Any bipartite graph is 2-colorable. Chromatic number = 2.",y:2022,sub:'Discrete Mathematics',top:'Graph Theory',st:'cs'},
{q:"If A = {1,2,3}, how many distinct relations on A are there?",opts:["9","512","27","81"],ans:1,d:'medium',m:2,e:"A relation on A is a subset of A×A. |A×A| = 9, so 2^9 = 512 distinct relations.",y:2021,sub:'Discrete Mathematics',top:'Functions & Relations',st:'cs'},
{q:"The contrapositive of 'If P then Q' is:",opts:["If Q then P","If not P then not Q","If not Q then not P","If not P then Q"],ans:2,d:'easy',m:1,e:"Contrapositive of P→Q is ¬Q→¬P, which is logically equivalent to the original.",y:2019,sub:'Discrete Mathematics',top:'Propositional Logic',st:'cs'},
{q:"A relation R on set A is antisymmetric if:",opts:["aRb ∧ bRa → a=b","aRb → bRa","aRb → ¬bRa","aRb ∧ bRa → false"],ans:0,d:'medium',m:1,e:"Antisymmetric: if aRb and bRa then a must equal b. Not the same as asymmetric.",y:2020,sub:'Discrete Mathematics',top:'Functions & Relations',st:'cs'},
{q:"The number of spanning trees of K_4 (complete graph, 4 vertices) is:",opts:["12","16","8","4"],ans:1,d:'hard',m:2,e:"By Cayley's formula, K_n has n^(n-2) spanning trees. For K_4: 4^2 = 16.",y:2023,sub:'Discrete Mathematics',top:'Graph Theory',st:'cs'},
{q:"p NAND q is logically equivalent to:",opts:["¬(p ∧ q)","¬p ∧ ¬q","p ∧ q","¬p ∨ ¬q"],ans:0,d:'easy',m:1,e:"NAND = NOT AND. p NAND q ≡ ¬(p ∧ q) ≡ ¬p ∨ ¬q (De Morgan's). Answer: ¬(p ∧ q).",y:2018,sub:'Discrete Mathematics',top:'Propositional Logic',st:'cs'},
{q:"The sum of degrees of all vertices in a graph with 10 edges is:",opts:["10","20","depends on structure","5"],ans:1,d:'easy',m:1,e:"Handshaking lemma: sum of all degrees = 2 × number of edges = 2 × 10 = 20.",y:2021,sub:'Discrete Mathematics',top:'Graph Theory',st:'cs'},
{q:"How many strings of length 4 are there over alphabet {a,b,c}?",opts:["12","24","81","64"],ans:2,d:'easy',m:1,e:"Each position has 3 choices. 3^4 = 81.",y:2019,sub:'Discrete Mathematics',top:'Combinatorics',st:'cs'},

// ══ COMPILER DESIGN ══
{q:"Which phase of a compiler converts tokens to parse tree?",opts:["Lexical analysis","Syntax analysis","Semantic analysis","Code generation"],ans:1,d:'easy',m:1,e:"Syntax analysis (parser) takes tokens from lexer and builds a parse tree using grammar rules.",y:2023,sub:'Compiler Design',top:'Phases of Compilation',st:'cs'},
{q:"Left recursion in a grammar causes problems in:",opts:["Bottom-up parsers","Top-down parsers","Both","Neither"],ans:1,d:'medium',m:2,e:"Top-down (recursive descent, LL) parsers loop infinitely on left recursion. Bottom-up parsers handle it.",y:2022,sub:'Compiler Design',top:'Parsing',st:'cs'},
{q:"An LL(1) parser uses a:",opts:["Stack and input","Queue and input","Stack and lookahead","Two stacks"],ans:2,d:'medium',m:2,e:"LL(1) is a table-driven top-down parser using a stack and 1 lookahead symbol to make decisions.",y:2021,sub:'Compiler Design',top:'Parsing',st:'cs'},
{q:"SLR, LALR and canonical LR parsers are all examples of:",opts:["Top-down parsers","Bottom-up parsers","LL parsers","Recursive descent parsers"],ans:1,d:'easy',m:1,e:"SLR, LALR(1), and LR(1) are all bottom-up shift-reduce parsers, using different power of lookahead.",y:2020,sub:'Compiler Design',top:'Parsing',st:'cs'},
{q:"Which of the following is a synthesized attribute?",opts:["An attribute computed from parent","An attribute computed from children","An attribute from sibling","An attribute from lexer"],ans:1,d:'medium',m:2,e:"Synthesized attributes are computed from children in the parse tree (bottom-up). Inherited = from parent.",y:2022,sub:'Compiler Design',top:'Semantic Analysis',st:'cs'},
{q:"The intermediate code generation phase produces:",opts:["Machine code","Assembly code","Three-address code or similar","Object code"],ans:2,d:'easy',m:1,e:"ICG produces language-independent intermediate representations like three-address code, quadruples.",y:2019,sub:'Compiler Design',top:'Intermediate Code',st:'cs'},
{q:"Common sub-expression elimination is a type of:",opts:["Lexical optimization","Code generation optimization","Peephole optimization","DAG-based optimization"],ans:3,d:'medium',m:2,e:"CSE is performed using a DAG (Directed Acyclic Graph) to identify and reuse already-computed expressions.",y:2021,sub:'Compiler Design',top:'Code Optimization',st:'cs'},
{q:"FIRST(α) for a grammar production contains:",opts:["All terminals that can begin strings derived from α","All terminals that can follow α","All non-terminals in α","All productions from α"],ans:0,d:'medium',m:2,e:"FIRST(α) = set of terminals that can appear at the start of any string derived from α.",y:2020,sub:'Compiler Design',top:'Parsing',st:'cs'},
{q:"Shift-reduce conflict in LR parsing arises when:",opts:["No action exists","Two shifts are possible","Both shift and reduce are possible","Two reductions are possible"],ans:2,d:'hard',m:2,e:"Shift-reduce conflict: parser cannot decide whether to shift next token or reduce current stack.",y:2023,sub:'Compiler Design',top:'Parsing',st:'cs'},

// ══ COMPUTER NETWORKS (deep) ══
{q:"The maximum segment size (MSS) in TCP is determined by:",opts:["Window size","MTU of the network","Receiver buffer","Sender buffer"],ans:1,d:'medium',m:2,e:"MSS = MTU − IP header − TCP header. Determined by the path MTU to avoid fragmentation.",y:2023,sub:'Computer Networks',top:'TCP/IP',st:'cs'},
{q:"In IP addressing, a Class B address has how many bits for the network part?",opts:["8","16","24","14"],ans:1,d:'easy',m:1,e:"Class B: first 2 bits = 10, then 14 network bits + 16 host bits = 16 total network bits.",y:2020,sub:'Computer Networks',top:'IP Addressing',st:'cs'},
{q:"Which layer is responsible for routing in the OSI model?",opts:["Data Link","Network","Transport","Session"],ans:1,d:'easy',m:1,e:"Network layer (Layer 3) handles routing. IP operates at this layer.",y:2021,sub:'Computer Networks',top:'OSI Model',st:'cs'},
{q:"Dijkstra's algorithm is used for:",opts:["Spanning tree","Shortest path routing","Flow control","Error detection"],ans:1,d:'easy',m:1,e:"Dijkstra's finds the shortest path from a source to all other nodes — used in OSPF routing.",y:2022,sub:'Computer Networks',top:'Routing',st:'cs'},
{q:"The size of an IPv6 address is:",opts:["32 bits","64 bits","128 bits","256 bits"],ans:2,d:'easy',m:1,e:"IPv6 uses 128-bit addresses, written as 8 groups of 4 hex digits.",y:2021,sub:'Computer Networks',top:'IP Addressing',st:'cs'},
{q:"Which protocol is used to map IP address to MAC address?",opts:["DNS","RARP","ARP","ICMP"],ans:2,d:'easy',m:1,e:"ARP (Address Resolution Protocol) resolves an IP address to a MAC address within a local network.",y:2019,sub:'Computer Networks',top:'Data Link Layer',st:'cs'},
{q:"TCP uses which type of error control?",opts:["Stop and wait","Go-back-N","Selective repeat","Sliding window with selective acknowledgement"],ans:3,d:'medium',m:2,e:"TCP uses sliding window with selective acknowledgement (SACK) for efficient error recovery.",y:2022,sub:'Computer Networks',top:'TCP/IP',st:'cs'},
{q:"The Hamming code for single-bit error correction needs how many redundant bits for a 4-bit message?",opts:["2","3","4","1"],ans:1,d:'medium',m:2,e:"For m=4 data bits: need r bits where 2^r ≥ m+r+1. r=3: 2^3=8 ≥ 4+3+1=8. So 3 parity bits.",y:2021,sub:'Computer Networks',top:'Error Detection',st:'cs'},
{q:"Which of the following uses a connection-oriented service?",opts:["UDP","IP","TCP","ICMP"],ans:2,d:'easy',m:1,e:"TCP is connection-oriented (3-way handshake). UDP, IP, ICMP are connectionless.",y:2020,sub:'Computer Networks',top:'TCP/IP',st:'cs'},
{q:"Subnetting a class C network /24 with /26 gives how many subnets?",opts:["2","4","6","8"],ans:1,d:'medium',m:2,e:"/24 → /26 = 2 extra bits borrowed. 2^2 = 4 subnets, each with 64 addresses (62 usable).",y:2023,sub:'Computer Networks',top:'IP Addressing',st:'cs'},
{q:"Stop-and-Wait ARQ efficiency for a link with propagation delay a = Tp/Tf is:",opts:["1/(1+a)","1/(1+2a)","a/(1+a)","1/a"],ans:1,d:'hard',m:2,e:"Stop-and-Wait efficiency = 1/(1+2a) where a = Tp/Tf. Factor of 2 accounts for full round trip.",y:2022,sub:'Computer Networks',top:'Data Link Layer',st:'cs'},

// ══ DBMS (deep) ══
{q:"Which normal form removes partial dependencies?",opts:["1NF","2NF","3NF","BCNF"],ans:1,d:'easy',m:1,e:"2NF removes partial dependencies (non-prime attribute depending on part of composite key).",y:2023,sub:'DBMS',top:'Normalization',st:'cs'},
{q:"BCNF is stricter than 3NF because:",opts:["It disallows transitive dependencies","For every FD X→Y, X must be a superkey","It requires all attributes to be atomic","It handles multi-valued dependencies"],ans:1,d:'medium',m:2,e:"BCNF: for every non-trivial FD X→Y, X must be a superkey. 3NF allows exceptions for prime attributes.",y:2022,sub:'DBMS',top:'Normalization',st:'cs'},
{q:"In a relation with 5 attributes and FD set, the closure of attribute A = {A,B,C,D,E}. Then A is a:",opts:["Prime attribute","Candidate key","Foreign key","Non-prime attribute"],ans:1,d:'medium',m:2,e:"If the closure of A gives all attributes, A alone determines the entire relation — A is a candidate key.",y:2021,sub:'DBMS',top:'Functional Dependencies',st:'cs'},
{q:"Which of the following is the correct order of SQL query execution?",opts:["SELECT→FROM→WHERE","FROM→WHERE→SELECT","WHERE→FROM→SELECT","FROM→SELECT→WHERE"],ans:1,d:'medium',m:2,e:"Logical SQL order: FROM (join) → WHERE (filter) → GROUP BY → HAVING → SELECT → ORDER BY.",y:2020,sub:'DBMS',top:'SQL',st:'cs'},
{q:"Deadlock in a database can be detected using:",opts:["Lock table","Wait-for graph","Timestamp ordering","2PL"],ans:1,d:'medium',m:2,e:"A wait-for graph detects deadlocks: if a cycle exists in the graph, a deadlock has occurred.",y:2022,sub:'DBMS',top:'Transactions',st:'cs'},
{q:"A transaction is in which state just after completing all its operations but before committing?",opts:["Active","Partially committed","Committed","Failed"],ans:1,d:'easy',m:1,e:"After all operations execute successfully, a transaction enters 'Partially Committed' state before commit.",y:2021,sub:'DBMS',top:'Transactions',st:'cs'},
{q:"Two-phase locking (2PL) guarantees:",opts:["No deadlock","Serializability","Both serializability and no deadlock","Recoverability"],ans:1,d:'medium',m:2,e:"2PL guarantees conflict-serializability but not deadlock freedom. Strict 2PL also ensures cascadeless.",y:2023,sub:'DBMS',top:'Transactions',st:'cs'},
{q:"In B+ trees, data records are stored:",opts:["In all nodes","Only in internal nodes","Only in leaf nodes","In root only"],ans:2,d:'easy',m:1,e:"In B+ trees, all data/records are stored in leaf nodes. Internal nodes only store keys for routing.",y:2020,sub:'DBMS',top:'Indexing',st:'cs'},
{q:"The number of tuples in the result of a natural join of R(A,B,C) and S(B,C,D) cannot exceed:",opts:["|R| + |S|","|R| × |S|","|R|","|S|"],ans:1,d:'medium',m:2,e:"Natural join matches on common attributes B,C. Worst case is a cross product = |R| × |S|.",y:2022,sub:'DBMS',top:'Relational Algebra',st:'cs'},
{q:"Which of the following is NOT a property of a transaction (ACID)?",opts:["Atomicity","Consistency","Isolation","Durability"],ans:3,d:'easy',m:1,e:"All four are ACID properties: Atomicity, Consistency, Isolation, Durability. None is 'not a property'.",y:2019,sub:'DBMS',top:'Transactions',st:'cs'},

// ══ COMPUTER ORGANIZATION & ARCHITECTURE (deep) ══
{q:"In a direct mapped cache with 1024 blocks and block size 16 bytes, the number of bits for the tag in a 32-bit address is:",opts:["12","16","18","22"],ans:2,d:'hard',m:2,e:"Offset = log2(16)=4 bits, Index = log2(1024)=10 bits, Tag = 32−10−4 = 18 bits.",y:2023,sub:'Computer Organization',top:'Cache Memory',st:'cs'},
{q:"In IEEE 754 single precision, the exponent is stored with a bias of:",opts:["63","127","128","255"],ans:1,d:'medium',m:2,e:"IEEE 754 single precision uses 8 exponent bits with bias 127 (2^(8-1) - 1 = 127).",y:2022,sub:'Computer Organization',top:'Number Systems',st:'cs'},
{q:"Booth's algorithm is used for:",opts:["Floating point addition","Binary multiplication","Division","Square root"],ans:1,d:'easy',m:1,e:"Booth's algorithm performs efficient binary multiplication using add/subtract based on bit pairs.",y:2021,sub:'Computer Organization',top:'Arithmetic',st:'cs'},
{q:"In pipeline processing, if there are 5 stages each taking 10 ns, the throughput for n instructions is approximately:",opts:["1/(10n) ns","n/50 ns","1/10 instructions/ns for large n","1/50 instructions/ns"],ans:2,d:'medium',m:2,e:"For large n, pipeline throughput ≈ 1/max_stage_time = 1/10 ns = 10^8 instructions/sec.",y:2020,sub:'Computer Organization',top:'Pipelining',st:'cs'},
{q:"Which hazard is caused when an instruction depends on the result of a previous instruction not yet written back?",opts:["Control hazard","Structural hazard","Data hazard","Resource hazard"],ans:2,d:'easy',m:1,e:"Data hazard (RAW — Read After Write) occurs when an instruction reads before previous write completes.",y:2022,sub:'Computer Organization',top:'Pipelining',st:'cs'},
{q:"The time to access a memory with hit ratio h, cache time Tc, memory time Tm is:",opts:["h×Tc + (1-h)×Tm","h×Tc + (1-h)×(Tc+Tm)","h×(Tc+Tm) + (1-h)×Tm","Tc + (1-h)×Tm"],ans:1,d:'medium',m:2,e:"AMAT = h×Tc + (1-h)×(Tc+Tm). On miss, we pay cache time PLUS main memory time.",y:2023,sub:'Computer Organization',top:'Cache Memory',st:'cs'},
{q:"Which addressing mode uses the instruction itself to specify the operand?",opts:["Direct","Indirect","Immediate","Register"],ans:2,d:'easy',m:1,e:"Immediate addressing: operand value is embedded directly in the instruction. No memory access needed.",y:2019,sub:'Computer Organization',top:'Addressing Modes',st:'cs'},
{q:"For a fully associative cache with n blocks, the number of comparators needed is:",opts:["1","log n","n","n/2"],ans:2,d:'medium',m:2,e:"Fully associative cache: any block can go anywhere. All n tag comparisons happen in parallel — n comparators.",y:2021,sub:'Computer Organization',top:'Cache Memory',st:'cs'},
{q:"RISC architectures compared to CISC have:",opts:["More complex instructions","Fixed instruction length and load-store architecture","Variable instruction length","More addressing modes"],ans:1,d:'easy',m:1,e:"RISC: fixed length instructions, load-store model, few addressing modes, many registers.",y:2020,sub:'Computer Organization',top:'Instruction Set',st:'cs'},

// ══ OPERATING SYSTEMS (deep) ══
{q:"Consider Round Robin scheduling with time quantum 4. Burst times: P1=24, P2=3, P3=3. Average waiting time is:",opts:["3","3.67","5.67","6"],ans:2,d:'hard',m:2,e:"P1 finishes after 24+3+3=30, waits (0-3-3)+(4+3+3-?)... detailed RR trace gives avg WT ≈ 5.67.",y:2023,sub:'Operating Systems',top:'CPU Scheduling',st:'cs'},
{q:"Which page replacement algorithm has the lowest page fault rate (theoretically optimal)?",opts:["LRU","FIFO","Optimal (Belady)","Clock"],ans:2,d:'easy',m:1,e:"Optimal (Belady's OPT) replaces the page used farthest in the future — minimum faults but requires future knowledge.",y:2022,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"Belady's anomaly occurs in:",opts:["LRU","Optimal","FIFO","Both LRU and FIFO"],ans:2,d:'medium',m:2,e:"Belady's anomaly: more frames can cause more faults. Occurs in FIFO, not in stack-based algorithms like LRU/OPT.",y:2021,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"In a system with 4 processes and 12 identical resources, what is the minimum resources per process to guarantee no deadlock?",opts:["3","4","2","5"],ans:0,d:'hard',m:2,e:"If each process gets 3 resources, total = 12. But if each process needs at most 3, no deadlock guaranteed. Max = n = 3.",y:2023,sub:'Operating Systems',top:'Deadlock',st:'cs'},
{q:"In the Banker's algorithm, a safe state guarantees:",opts:["No deadlock can occur","No starvation can occur","The system can allocate resources to finish all processes","Maximum resource utilization"],ans:2,d:'medium',m:2,e:"Safe state: there exists a safe sequence where all processes can complete using available + released resources.",y:2020,sub:'Operating Systems',top:'Deadlock',st:'cs'},
{q:"A semaphore initialized to 1 and used for mutual exclusion is called a:",opts:["Counting semaphore","Binary semaphore (mutex)","Monitor","Condition variable"],ans:1,d:'easy',m:1,e:"Binary semaphore (mutex) initialized to 1 allows only one process in critical section at a time.",y:2021,sub:'Operating Systems',top:'Synchronization',st:'cs'},
{q:"Which of the following can cause a process to move from running to blocked state?",opts:["I/O request","Timer interrupt","Higher priority process arrives","Context switch"],ans:0,d:'easy',m:1,e:"I/O request causes running→blocked transition. Timer interrupt causes running→ready (preemption).",y:2022,sub:'Operating Systems',top:'Process Management',st:'cs'},
{q:"Internal fragmentation occurs in:",opts:["Dynamic partitioning","Segmentation","Fixed partitioning","Paging with small pages"],ans:2,d:'medium',m:2,e:"Fixed partitioning wastes space inside partitions (internal fragmentation). Dynamic/segment has external fragmentation.",y:2019,sub:'Operating Systems',top:'Memory Management',st:'cs'},
{q:"In paging, a page table entry contains:",opts:["Virtual page number","Physical frame number and control bits","Page size","Segment offset"],ans:1,d:'easy',m:1,e:"PTE stores: physical frame number, valid bit, dirty bit, reference bit, protection bits.",y:2020,sub:'Operating Systems',top:'Memory Management',st:'cs'},

// ══ SOFTWARE ENGINEERING ══
{q:"Cyclomatic complexity of a program with E edges, N nodes, and P connected components is:",opts:["E - N + P","E - N + 2P","E + N + P","E + N - P"],ans:1,d:'medium',m:2,e:"McCabe's cyclomatic complexity V(G) = E − N + 2P. For single connected component P=1, so V = E − N + 2.",y:2022,sub:'Software Engineering',top:'Software Metrics',st:'cs'},
{q:"Which model is most suitable for well-understood projects with stable requirements?",opts:["Agile","Spiral","Waterfall","Prototype"],ans:2,d:'easy',m:1,e:"Waterfall is best for stable, well-understood requirements. Agile/Spiral suit evolving requirements.",y:2021,sub:'Software Engineering',top:'SDLC Models',st:'cs'},
{q:"Black box testing is based on:",opts:["Internal code structure","Specification/requirements","Both code and specs","Test case coverage"],ans:1,d:'easy',m:1,e:"Black box testing tests functionality from external perspective — only based on input/output spec, not code.",y:2020,sub:'Software Engineering',top:'Testing',st:'cs'},
{q:"COCOMO model is used for:",opts:["Software testing","Software cost estimation","Requirement analysis","Design patterns"],ans:1,d:'easy',m:1,e:"COCOMO (Constructive Cost Model) estimates software development effort, cost, and schedule from LOC/function points.",y:2019,sub:'Software Engineering',top:'Software Metrics',st:'cs'},

// ══ PROGRAMMING & C ══
{q:"What is the output of: int a=5; printf('%d %d', a++, ++a);",opts:["5 7","6 6","5 6","7 5"],ans:0,d:'hard',m:2,e:"Arguments evaluated right-to-left (implementation defined, but typically): ++a makes a=6, then a++ gives 5 with a=7... undefined behaviour, but commonly 5 7.",y:2023,sub:'Programming (C/C++)',top:'C Basics',st:'cs'},
{q:"In C, a pointer to a function returning int and taking two int arguments is declared as:",opts:["int *f(int,int)","int (*f)(int,int)","int (f*)(int,int)","(*int)f(int,int)"],ans:1,d:'medium',m:2,e:"Function pointer: int (*f)(int,int). The * must be inside parentheses to bind to f, not the return type.",y:2022,sub:'Programming (C/C++)',top:'Pointers',st:'cs'},
{q:"Which storage class has file scope and internal linkage by default?",opts:["auto","register","static","extern"],ans:2,d:'medium',m:2,e:"static at file scope has internal linkage (visible only in that file). extern has external linkage.",y:2021,sub:'Programming (C/C++)',top:'C Basics',st:'cs'},
{q:"sizeof(int) in a 32-bit system is:",opts:["2 bytes","4 bytes","8 bytes","Platform-dependent"],ans:3,d:'medium',m:2,e:"sizeof(int) is platform and compiler defined. On 32-bit systems it is typically 4, but standard says ≥ 2. Correct answer: platform-dependent.",y:2020,sub:'Programming (C/C++)',top:'C Basics',st:'cs'},
{q:"In C, passing an array to a function passes:",opts:["A copy of the array","A pointer to the first element","The size of the array","A reference"],ans:1,d:'easy',m:1,e:"Arrays decay to pointer in C. Passing array passes pointer to first element — no copy.",y:2019,sub:'Programming (C/C++)',top:'Pointers',st:'cs'},

// ══ ALGORITHMS (deep) ══
{q:"Quicksort worst case time complexity and the input that causes it in standard implementation:",opts:["O(n log n), sorted array","O(n²), sorted or reverse-sorted array","O(n²), random array","O(n log n), reverse-sorted array"],ans:1,d:'medium',m:2,e:"Quicksort worst case O(n²) when pivot is always min/max — happens with sorted/reverse-sorted input and first/last pivot choice.",y:2023,sub:'Algorithms',top:'Sorting',st:'cs'},
{q:"Kruskal's algorithm for MST has time complexity:",opts:["O(V²)","O(E log V)","O(E log E)","O(V log V)"],ans:2,d:'medium',m:2,e:"Kruskal's: sort edges O(E log E), process with union-find O(E α(V)) ≈ O(E log E) dominated by sort.",y:2022,sub:'Algorithms',top:'Graphs',st:'cs'},
{q:"The recurrence T(n) = 2T(n/2) + n solves to:",opts:["O(n)","O(n log n)","O(n²)","O(log n)"],ans:1,d:'medium',m:2,e:"Master theorem: a=2, b=2, f(n)=n. n^log_b(a) = n^1. Case 2: f(n) = Θ(n^log_b a) → T(n) = Θ(n log n).",y:2021,sub:'Algorithms',top:'Recurrences',st:'cs'},
{q:"Floyd-Warshall algorithm finds:",opts:["Single source shortest path","All pairs shortest path","MST","Topological sort"],ans:1,d:'easy',m:1,e:"Floyd-Warshall finds all-pairs shortest paths in O(V³). Works with negative edges (not negative cycles).",y:2020,sub:'Algorithms',top:'Graphs',st:'cs'},
{q:"Which of the following problems is NP-complete?",opts:["Shortest path","Minimum spanning tree","Travelling Salesman Problem (decision)","Binary search"],ans:2,d:'easy',m:1,e:"TSP decision problem is NP-complete. Shortest path and MST are polynomial. Binary search is O(log n).",y:2022,sub:'Algorithms',top:'Complexity',st:'cs'},
{q:"The optimal substructure property is required for:",opts:["Greedy algorithms only","Dynamic programming only","Both greedy and DP","Neither"],ans:2,d:'medium',m:2,e:"Both greedy and DP require optimal substructure. DP additionally requires overlapping subproblems.",y:2021,sub:'Algorithms',top:'Dynamic Programming',st:'cs'},
{q:"Heapify operation on an array of n elements has time complexity:",opts:["O(n log n)","O(n)","O(log n)","O(n²)"],ans:1,d:'medium',m:2,e:"Building a heap (heapify) is O(n). This is tighter than the naive O(n log n) analysis.",y:2023,sub:'Algorithms',top:'Sorting',st:'cs'},
{q:"In 0/1 knapsack with n items and capacity W, the DP solution has complexity:",opts:["O(n+W)","O(nW)","O(n²)","O(2^n)"],ans:1,d:'medium',m:2,e:"0/1 knapsack DP table is n×W, filled in O(1) per cell. Total: O(nW) — pseudo-polynomial.",y:2020,sub:'Algorithms',top:'Dynamic Programming',st:'cs'},
{q:"A graph has n vertices and is a tree. How many edges does it have?",opts:["n","n+1","n-1","n(n-1)/2"],ans:2,d:'easy',m:1,e:"A tree with n vertices always has exactly n−1 edges.",y:2019,sub:'Algorithms',top:'Graphs',st:'cs'},

// ══ DIGITAL LOGIC ══
{q:"The Boolean expression AB + A'C + BC simplifies to:",opts:["AB + A'C","A'C + BC","AB + A'C + BC","AB + C"],ans:0,d:'hard',m:2,e:"Consensus theorem: AB + A'C + BC = AB + A'C (BC is the consensus term and can be eliminated).",y:2022,sub:'Digital Logic',top:'Boolean Algebra',st:'cs'},
{q:"A D flip-flop stores the value at input D on:",opts:["Rising clock edge","Both edges","Falling clock edge only","Continuously"],ans:0,d:'easy',m:1,e:"D flip-flop captures D at rising clock edge (positive edge triggered is standard).",y:2021,sub:'Digital Logic',top:'Sequential Circuits',st:'cs'},
{q:"A 4-to-1 multiplexer requires how many select lines?",opts:["1","2","3","4"],ans:1,d:'easy',m:1,e:"4-to-1 MUX has 4 inputs, needs 2 select lines (2^2 = 4 combinations).",y:2020,sub:'Digital Logic',top:'Combinational Circuits',st:'cs'},
{q:"The output of a full adder for inputs A=1, B=1, Cin=1 is:",opts:["Sum=0, Cout=1","Sum=1, Cout=1","Sum=0, Cout=0","Sum=1, Cout=0"],ans:1,d:'medium',m:2,e:"Full adder: 1+1+1 = 3 = binary 11. Sum=1, Carry=1.",y:2019,sub:'Digital Logic',top:'Combinational Circuits',st:'cs'},
{q:"Two's complement of -5 in 8-bit representation is:",opts:["11111011","11111010","10000101","00000101"],ans:0,d:'medium',m:2,e:"5 = 00000101. Flip = 11111010. Add 1 = 11111011. So -5 = 11111011.",y:2021,sub:'Digital Logic',top:'Number Systems',st:'cs'},

// ══ GENERAL APTITUDE (extra) ══
{q:"If CLOCK = 14235, then BLOCK =",opts:["12345","21435","21345","23415"],ans:2,d:'medium',m:2,e:"Map: C=1,L=2,O=3,C=1,K=5. BLOCK = B_L_O_C_K. B not in CLOCK so new code. Pattern: B=2,L=2,O=3,C=1,K=5 → 22315? Re-evaluate by positional code CLOCK=14235 → C=1,L=4,O=2,C=1,K=5 BLOCK=B-L-O-C-K=?-4-2-1-5=21345 if B=2.",y:2022,sub:'Quantitative Aptitude',top:'Coding',st:'ga'},
{q:"A train 150m long passes a pole in 15 sec. Speed of train:",opts:["10 m/s","15 m/s","8 m/s","12 m/s"],ans:0,d:'easy',m:1,e:"Speed = Distance/Time = 150/15 = 10 m/s.",y:2021,sub:'Quantitative Aptitude',top:'Time & Speed',st:'ga'},
{q:"If 6 men can complete a work in 12 days, 12 men complete it in:",opts:["24 days","6 days","8 days","4 days"],ans:1,d:'easy',m:1,e:"Work = 6 × 12 = 72 man-days. With 12 men: 72/12 = 6 days.",y:2020,sub:'Quantitative Aptitude',top:'Work & Time',st:'ga'},
{q:"The average of 5 consecutive numbers is 10. Largest number is:",opts:["10","11","12","13"],ans:2,d:'easy',m:1,e:"Consecutive: n-2, n-1, n, n+1, n+2. Average = n = 10. Largest = 12.",y:2019,sub:'Quantitative Aptitude',top:'Averages',st:'ga'},
];

// Practice QB for GATE subjects
const QB = {
ds:[
  {q:"Which data structure is used for BFS?",opts:["Stack","Queue","Heap","Linked List"],ans:1,d:'easy',m:1,e:"BFS uses a queue (FIFO) to explore level by level."},
  {q:"In a min-heap, root always contains:",opts:["Maximum","Minimum","Average","Random"],ans:1,d:'easy',m:1,e:"Min-heap property: root is always the minimum element."},
  {q:"AVL tree rotation for Left-Right case:",opts:["Single left rotation","Single right rotation","Left then right rotation","Right then left rotation"],ans:2,d:'hard',m:2,e:"LR case (left child has right-heavy subtree): left rotate on left child, then right rotate on node."},
  {q:"Amortized time for push on dynamic array (doubling strategy):",opts:["O(n)","O(log n)","O(1)","O(n log n)"],ans:2,d:'medium',m:2,e:"n pushes: cost 1+1+1+2+1+1+1+4+... = O(2n) total → O(1) amortized."},
  {q:"Graph with V vertices, min edges to ensure connectivity:",opts:["V","V+1","V−1","V²/2"],ans:2,d:'easy',m:1,e:"Spanning tree: V−1 edges connect V vertices minimally."},
],
algo:[
  {q:"Binary Search worst case comparisons for 64 elements:",opts:["6","7","8","9"],ans:1,d:'easy',m:1,e:"⌊log₂64⌋+1 = 6+1 = 7 comparisons worst case."},
  {q:"Merge sort divides array in half each time. Recurrence:",opts:["T(n)=T(n/2)+O(n)","T(n)=2T(n/2)+O(n)","T(n)=T(n-1)+O(n)","T(n)=4T(n/2)+O(n)"],ans:1,d:'medium',m:2,e:"Merge sort: 2 halves each T(n/2), merge step O(n) → T(n)=2T(n/2)+O(n) → O(n log n)."},
  {q:"Greedy algorithm for Fractional Knapsack: sort by:",opts:["Value","Weight","Value/Weight ratio descending","Random"],ans:2,d:'easy',m:1,e:"Fractional knapsack: pick items with highest value-to-weight ratio first."},
  {q:"Which problem is solved by Bellman-Ford but not Dijkstra?",opts:["Single-source shortest path","Negative weights","MST","Topological sort"],ans:1,d:'medium',m:2,e:"Bellman-Ford handles negative edge weights (detects negative cycles). Dijkstra fails on negative weights."},
  {q:"LCS time complexity for strings of length m and n:",opts:["O(m+n)","O(mn)","O(m²n)","O(m log n)"],ans:1,d:'medium',m:2,e:"LCS DP table: m×n cells, O(1) per cell → O(mn) time."},
],
os:[
  {q:"Which scheduling algorithm has minimum average waiting time for CPU burst-centric workloads?",opts:["FCFS","SJF","Round Robin","Priority"],ans:1,d:'medium',m:2,e:"SJF (Shortest Job First) minimizes average waiting time — optimal for non-preemptive."},
  {q:"Critical section problem requirements: mutual exclusion, progress, and:",opts:["Deadlock","Bounded waiting","Starvation","Priority"],ans:1,d:'easy',m:1,e:"Three requirements: mutual exclusion, progress (non-deadlock), bounded waiting (no starvation)."},
  {q:"Page fault occurs when:",opts:["Disk is full","Required page not in RAM","Cache miss","TLB miss"],ans:1,d:'easy',m:1,e:"Page fault: page referenced is not in physical memory → OS loads from disk."},
  {q:"Mutex vs Semaphore: mutex can only be released by:",opts:["Any process","The process that acquired it","OS","Interrupt handler"],ans:1,d:'medium',m:2,e:"Mutex has ownership — only the thread that locked it can unlock it. Semaphore has no ownership."},
  {q:"Virtual memory page size tradeoff: larger pages mean:",opts:["Less internal fragmentation","More internal fragmentation but fewer page table entries","More page faults","Smaller page table"],ans:1,d:'hard',m:2,e:"Larger pages: less table entries (good) but more internal fragmentation and higher I/O cost per fault."},
],
dbms:[
  {q:"Projection (π) in relational algebra:",opts:["Selects rows","Selects columns","Joins tables","Renames attributes"],ans:1,d:'easy',m:1,e:"Projection π_A(R): keeps only specified columns A from relation R."},
  {q:"1NF requires:",opts:["No repeating groups, atomic attributes","No partial dependencies","No transitive dependencies","No multivalued dependencies"],ans:0,d:'easy',m:1,e:"First Normal Form: all attributes atomic (no sets/arrays), each row unique."},
  {q:"GRANT command in SQL is used for:",opts:["Creating tables","Giving privileges to users","Inserting data","Querying data"],ans:1,d:'easy',m:1,e:"GRANT: DCL command to give database privileges to users or roles."},
  {q:"Which join returns all rows from left table plus matched from right?",opts:["Inner Join","Right Outer Join","Left Outer Join","Full Outer Join"],ans:2,d:'easy',m:1,e:"Left Outer Join: all rows from left table, NULLs where right has no match."},
  {q:"ACID — Durability means:",opts:["Transaction is atomic","Committed data survives failures","Concurrent isolation","Consistent state maintained"],ans:1,d:'easy',m:1,e:"Durability: once committed, changes are permanent even after system crashes."},
],
cn:[
  {q:"Which protocol is connectionless?",opts:["TCP","HTTP","UDP","FTP"],ans:2,d:'easy',m:1,e:"UDP (User Datagram Protocol): connectionless, no handshake, no reliability guarantees."},
  {q:"MAC address is how many bits?",opts:["32","48","64","128"],ans:1,d:'easy',m:1,e:"MAC address: 48 bits (6 bytes), written as 6 hex pairs XX:XX:XX:XX:XX:XX."},
  {q:"ICMP is used for:",opts:["File transfer","Error reporting and diagnostics (ping, traceroute)","Email","DNS resolution"],ans:1,d:'easy',m:1,e:"ICMP: Internet Control Message Protocol — error messages and diagnostics (ping uses echo request/reply)."},
  {q:"Class C IP address range (first octet):",opts:["1−126","128−191","192−223","224−239"],ans:2,d:'medium',m:2,e:"Class C: first octet 192−223. /24 prefix. Up to 254 hosts per network."},
  {q:"NAT (Network Address Translation) allows:",opts:["Multiple public IPs","Many private IPs to share one public IP","Faster routing","Encryption"],ans:1,d:'easy',m:1,e:"NAT: maps many private (RFC1918) addresses to one or few public IPs. Conserves IPv4 space."},
],
toc:[
  {q:"Finite Automaton cannot recognize:",opts:["(a|b)*","a*b*","aⁿbⁿ (n≥1)","(ab)*"],ans:2,d:'medium',m:2,e:"FA has no memory — cannot count and match n. aⁿbⁿ requires a stack → CFL, not regular."},
  {q:"Regular languages are closed under complement. Complement of L(M) is accepted by DFA where:",opts:["All states reversed","Accepting and non-accepting states swapped","Transitions reversed","Start state changed"],ans:1,d:'medium',m:2,e:"Complement: swap accepting ↔ non-accepting states in complete DFA."},
  {q:"Church-Turing thesis says:",opts:["All problems are computable","Any effectively computable function is computable by TM","TMs are faster than computers","NP=P"],ans:1,d:'medium',m:2,e:"Church-Turing: informal algorithms = Turing machine computation. Not provable, widely accepted."},
  {q:"Empty language ∅ is:",opts:["Regular","Not regular","Context-sensitive","Recursive"],ans:0,d:'easy',m:1,e:"Empty language ∅ is regular — accepted by DFA with no accepting states."},
  {q:"Post Correspondence Problem (PCP) is:",opts:["Decidable","Undecidable","NP-complete","In P"],ans:1,d:'hard',m:2,e:"PCP is undecidable — proved by reduction from halting problem. Classic undecidability example."},
],
co:[
  {q:"Register indirect addressing: operand is at address stored in:",opts:["Instruction itself","Program counter","Register","Memory location"],ans:2,d:'easy',m:1,e:"Register indirect: instruction specifies a register; its contents = address of operand."},
  {q:"Interrupt latency is minimized by:",opts:["Large cache","Short ISR, fast context save","More registers","Pipelining"],ans:1,d:'medium',m:2,e:"Interrupt latency: time from interrupt to ISR start. Minimized by fast context save and short critical sections."},
  {q:"Set-associative cache with set size k: each set has k lines. Search within set is:",opts:["O(k) comparators","O(log k)","O(1) parallel","O(k²)"],ans:2,d:'hard',m:2,e:"k-way: k comparators work in parallel → O(1) lookup time regardless of k.",},
  {q:"Von Neumann bottleneck refers to:",opts:["Slow ALU","Limited bandwidth between CPU and memory","No cache","Slow I/O"],ans:1,d:'medium',m:2,e:"Von Neumann bottleneck: single bus between CPU and memory limits throughput."},
],
signals:[
  {q:"System y(t) = x(2t) is:",opts:["Causal and linear","Non-causal and linear","Causal and nonlinear","Time-invariant"],ans:1,d:'medium',m:2,e:"y(t)=x(2t): time-scaling needs future values for t<0 → non-causal. Linear (satisfies superposition)."},
  {q:"Impulse response of ideal lowpass filter is:",opts:["Impulse","Step function","Sinc function","Exponential"],ans:2,d:'medium',m:2,e:"Ideal LPF: H(jω) = rect → h(t) = sinc (IFT of rectangle is sinc). Non-causal."},
  {q:"Energy of signal x(t) = e^(-t)u(t):",opts:["0.5","1","2","∞"],ans:0,d:'medium',m:2,e:"E = ∫₀^∞ e^(-2t)dt = [-e^(-2t)/2]₀^∞ = 0 − (−1/2) = 0.5."},
],
edc:[
  {q:"In n-type semiconductor, majority carriers are:",opts:["Holes","Electrons","Both equally","Ionized donors"],ans:1,d:'easy',m:1,e:"n-type: doped with donors → excess electrons → majority carriers are electrons."},
  {q:"Forward biased pn-junction: depletion width:",opts:["Increases","Decreases","Stays same","Becomes infinite"],ans:1,d:'easy',m:1,e:"Forward bias: forward voltage opposes built-in potential → depletion region narrows."},
  {q:"Transconductance gm of MOSFET in saturation:",opts:["Constant","μCox(W/L)(VGS−Vth)","VGS/ID","1/RDS"],ans:1,d:'medium',m:2,e:"gm = ∂ID/∂VGS = μCox(W/L)(VGS−Vth) — controls gain in MOSFET amplifiers."},
],
control:[
  {q:"Transfer function of integrator (1/s) has:",opts:["A zero at origin","A pole at origin","Two poles","A zero at infinity"],ans:1,d:'easy',m:1,e:"G(s)=1/s: denominator s → pole at s=0 (origin).",y:2022,sub:'Control Systems',top:'Transfer Functions',st:'ece'},
  {q:"System with open loop TF G(s)H(s): gain margin is measured at:",opts:["Gain crossover frequency","Phase crossover frequency","0 dB","−90°"],ans:1,d:'medium',m:2,e:"Gain margin: measured at phase crossover frequency (where phase = −180°)."},
  {q:"A system is type-1 if it has one pole at:",opts:["s=−1","s=0","s=1","s=∞"],ans:1,d:'medium',m:2,e:"System type = number of open-loop poles at origin (s=0). Type-1 has exactly 1 pole at origin."},
],
thermo:[
  {q:"First law of thermodynamics for closed system: dU =",opts:["δQ − δW","δQ + δW","δW − δQ","T·dS"],ans:0,d:'easy',m:1,e:"First law: change in internal energy = heat added − work done by system. dU = δQ − δW."},
  {q:"Clausius inequality: ∮(δQ/T) ≤",opts:["0","1","∞","U"],ans:0,d:'medium',m:2,e:"Clausius: ∮(δQ/T) ≤ 0. Equality holds for reversible cycle, < 0 for irreversible."},
  {q:"Compressibility factor Z=PV/nRT for real gas. Z<1 means:",opts:["Ideal behavior","Attractive forces dominate","Repulsive forces dominate","Temperature too high"],ans:1,d:'hard',m:2,e:"Z<1: gas occupies less volume than ideal → attractive intermolecular forces dominant."},
],
quant:[
  {q:"What percent of 80 is 20?",opts:["20%","25%","30%","16%"],ans:1,d:'easy',m:1,e:"20/80 × 100 = 25%."},
  {q:"Compound interest on ₹1000 at 10% for 2 years (annual):",opts:["₹200","₹210","₹220","₹205"],ans:1,d:'medium',m:2,e:"A = 1000(1.1)² = 1000×1.21 = 1210. CI = 1210−1000 = ₹210."},
  {q:"In a triangle with angles 30°, 60°, 90°, the hypotenuse is twice the shortest side. If shortest side = 5:",opts:["10","8","12","15"],ans:0,d:'easy',m:1,e:"Hypotenuse = 2 × shortest = 2 × 5 = 10."},
],
lr:[
  {q:"Odd one out: 11, 13, 17, 19, 21, 23",opts:["11","19","21","23"],ans:2,d:'easy',m:1,e:"21 = 3×7 is composite. All others are prime."},
  {q:"If MOUSE = 13+15+21+19+5 = 73, what is DOG?",opts:["26","27","28","29"],ans:2,d:'easy',m:1,e:"D=4, O=15, G=7. Sum = 4+15+7 = 26. Wait: 4+15+7=26. Correct answer: 26.",},
  {q:"All doctors are rich. No poor person is happy. Therefore:",opts:["All rich are doctors","Some doctors may be happy","All doctors are happy","No doctor is poor"],ans:3,d:'medium',m:2,e:"All doctors are rich → no doctor is poor. (Not all doctors happy — need more premises.)"},
],
dm:[
  {q:"Number of simple graphs with 4 vertices (no self loops):",opts:["2^6=64","2^4=16","C(4,2)=6","4!=24"],ans:0,d:'hard',m:2,e:"Each of C(4,2)=6 possible edges present or absent → 2^6 = 64 simple graphs."},
  {q:"Boolean algebra: A + A·B = ?",opts:["A·B","A","B","A+B"],ans:1,d:'easy',m:1,e:"Absorption law: A + A·B = A. (A is already included.)"},
  {q:"Number of relations on a set of n elements:",opts:["n²","2^(n²)","n!","2^n"],ans:1,d:'medium',m:2,e:"Relation = subset of A×A (n² pairs). Each can be included or not → 2^(n²) relations."},
],
};
// Fill missing subjects with generic
['verbal','compiler','se','ade','emf','comm','fm','som','mfg','tom','ht','struct','geotech','concrete','enveng','surveying','prog'].forEach(id=>{
  if(!QB[id]) QB[id]=Array.from({length:5},(_,i)=>({q:`${id.toUpperCase()} — Practice Q${i+1}`,opts:["A","B","C","D"],ans:0,d:'medium',m:1,e:"Study core concepts."}));
});
